from org.modelio.api.modelio import Modelio
def isFragmentDeployed(name):
  for f in Modelio.getInstance().getMetamodelService().getMetamodel().getFragments():
    if name == f.getName():
      return True
  return False

if isFragmentDeployed("Archimate"):
  ''' imports of archimate_implementation.api '''
  from org.modelio.archimate.metamodel.core.generic.composite import CompositeElement
  from org.modelio.archimate.metamodel.core.generic.composite import Grouping
  from org.modelio.archimate.metamodel.core.generic.composite import Location
  from org.modelio.archimate.metamodel.core.generic.motivation import MotivationElement
  from org.modelio.archimate.metamodel.core.generic import ActiveStructureElement
  from org.modelio.archimate.metamodel.core.generic import BehaviorElement
  from org.modelio.archimate.metamodel.core.generic import Event
  from org.modelio.archimate.metamodel.core.generic import ExternalActiveStructureElement
  from org.modelio.archimate.metamodel.core.generic import ExternalBehaviorElement
  from org.modelio.archimate.metamodel.core.generic import InternalActiveStructureElement
  from org.modelio.archimate.metamodel.core.generic import InternalBehaviorElement
  from org.modelio.archimate.metamodel.core.generic import PassiveStructureElement
  from org.modelio.archimate.metamodel.core.generic import StructureElement
  from org.modelio.archimate.metamodel.core.structure import ArchimateProject
  from org.modelio.archimate.metamodel.core.structure import Folder
  from org.modelio.archimate.metamodel.core.structure import Model
  from org.modelio.archimate.metamodel.core.structure import ViewPoint
  from org.modelio.archimate.metamodel.core.structure.folder import BusinessFolder
  from org.modelio.archimate.metamodel.core.structure.folder import StrategyFolder
  from org.modelio.archimate.metamodel.core.structure.folder import MotivationFolder
  from org.modelio.archimate.metamodel.core.structure.folder import ApplicationFolder
  from org.modelio.archimate.metamodel.core.structure.folder import TechnologyFolder
  from org.modelio.archimate.metamodel.core.structure.folder import PhysicalFolder
  from org.modelio.archimate.metamodel.core.structure.folder import ImplementationFolder
  from org.modelio.archimate.metamodel.core import Concept
  from org.modelio.archimate.metamodel.core import Element
  from org.modelio.archimate.metamodel.core import Relationship
  from org.modelio.archimate.metamodel.core import RelationshipConnector
  from org.modelio.archimate.metamodel.core import ArchimateAbstractElement
  from org.modelio.archimate.metamodel.core import ArchimateView
  from org.modelio.archimate.metamodel.core import ViewPointDiagram
  from org.modelio.archimate.metamodel.relationships.structural import Aggregation
  from org.modelio.archimate.metamodel.relationships.structural import Assignment
  from org.modelio.archimate.metamodel.relationships.structural import Composition
  from org.modelio.archimate.metamodel.relationships.structural import Realization
  from org.modelio.archimate.metamodel.relationships.structural import StructuralRelationship
  from org.modelio.archimate.metamodel.relationships.dependency import Access
  from org.modelio.archimate.metamodel.relationships.dependency import DependencyRelationship
  from org.modelio.archimate.metamodel.relationships.dependency import Influence
  from org.modelio.archimate.metamodel.relationships.dependency import Serving
  from org.modelio.archimate.metamodel.relationships.dependency import AccessMode
  from org.modelio.archimate.metamodel.relationships.dependency import InfluenceStrength
  from org.modelio.archimate.metamodel.relationships.dynamic import DynamicRelationship
  from org.modelio.archimate.metamodel.relationships.dynamic import Flow
  from org.modelio.archimate.metamodel.relationships.dynamic import Triggering
  from org.modelio.archimate.metamodel.relationships.other import Association
  from org.modelio.archimate.metamodel.relationships.other import Junction
  from org.modelio.archimate.metamodel.relationships.other import OtherRelationship
  from org.modelio.archimate.metamodel.relationships.other import Specialization
  from org.modelio.archimate.metamodel.relationships.other import OrJunction
  from org.modelio.archimate.metamodel.relationships.other import AndJunction
  from org.modelio.archimate.metamodel import ArchimateMetamodel
  from org.modelio.archimate.metamodel.layers.motivation import Stakeholder
  from org.modelio.archimate.metamodel.layers.motivation import Meaning
  from org.modelio.archimate.metamodel.layers.motivation import Value
  from org.modelio.archimate.metamodel.layers.motivation import Driver
  from org.modelio.archimate.metamodel.layers.motivation import Assessment
  from org.modelio.archimate.metamodel.layers.motivation import Goal
  from org.modelio.archimate.metamodel.layers.motivation import Outcome
  from org.modelio.archimate.metamodel.layers.motivation import Principle
  from org.modelio.archimate.metamodel.layers.motivation import Requirement
  from org.modelio.archimate.metamodel.layers.motivation import Constraint
  from org.modelio.archimate.metamodel.layers.implementation_and_migration import WorkPackage
  from org.modelio.archimate.metamodel.layers.implementation_and_migration import Deliverable
  from org.modelio.archimate.metamodel.layers.implementation_and_migration import ImplementationEvent
  from org.modelio.archimate.metamodel.layers.implementation_and_migration import Plateau
  from org.modelio.archimate.metamodel.layers.implementation_and_migration import Gap
  from org.modelio.archimate.metamodel.layers.business.behavior import BusinessProcess
  from org.modelio.archimate.metamodel.layers.business.behavior import BusinessFunction
  from org.modelio.archimate.metamodel.layers.business.behavior import BusinessInteraction
  from org.modelio.archimate.metamodel.layers.business.behavior import BusinessEvent
  from org.modelio.archimate.metamodel.layers.business.behavior import BusinessService
  from org.modelio.archimate.metamodel.layers.business.composite import Product
  from org.modelio.archimate.metamodel.layers.business.structure.active import BusinessActor
  from org.modelio.archimate.metamodel.layers.business.structure.active import BusinessRole
  from org.modelio.archimate.metamodel.layers.business.structure.active import BusinessCollaboration
  from org.modelio.archimate.metamodel.layers.business.structure.active import BusinessInterface
  from org.modelio.archimate.metamodel.layers.business.structure.passive import BusinessObject
  from org.modelio.archimate.metamodel.layers.business.structure.passive import Contract
  from org.modelio.archimate.metamodel.layers.business.structure.passive import Representation
  from org.modelio.archimate.metamodel.layers.business import BusinessInternalActiveStructureElement
  from org.modelio.archimate.metamodel.layers.business import BusinessInternalBehaviorElement
  from org.modelio.archimate.metamodel.layers.business import BusinessPassiveStructureElement
  from org.modelio.archimate.metamodel.layers.application.behavior import ApplicationFunction
  from org.modelio.archimate.metamodel.layers.application.behavior import ApplicationInteraction
  from org.modelio.archimate.metamodel.layers.application.behavior import ApplicationProcess
  from org.modelio.archimate.metamodel.layers.application.behavior import ApplicationEvent
  from org.modelio.archimate.metamodel.layers.application.behavior import ApplicationService
  from org.modelio.archimate.metamodel.layers.application.behavior import ApplicationInternalBehaviorElement
  from org.modelio.archimate.metamodel.layers.application.structure.active import ApplicationComponent
  from org.modelio.archimate.metamodel.layers.application.structure.active import ApplicationCollaboration
  from org.modelio.archimate.metamodel.layers.application.structure.active import ApplicationInterface
  from org.modelio.archimate.metamodel.layers.application.structure.passive import DataObject
  from org.modelio.archimate.metamodel.layers.technology.behavior import TechnologyFunction
  from org.modelio.archimate.metamodel.layers.technology.behavior import TechnologyProcess
  from org.modelio.archimate.metamodel.layers.technology.behavior import TechnologyEvent
  from org.modelio.archimate.metamodel.layers.technology.behavior import TechnologyService
  from org.modelio.archimate.metamodel.layers.technology.behavior import TechnologyInternalBehaviorElement
  from org.modelio.archimate.metamodel.layers.technology.behavior import TechnologyInteraction
  from org.modelio.archimate.metamodel.layers.technology.structure.active import Node
  from org.modelio.archimate.metamodel.layers.technology.structure.active import Device
  from org.modelio.archimate.metamodel.layers.technology.structure.active import SystemSoftware
  from org.modelio.archimate.metamodel.layers.technology.structure.active import TechnologyInterface
  from org.modelio.archimate.metamodel.layers.technology.structure.active import Path
  from org.modelio.archimate.metamodel.layers.technology.structure.active import CommunicationNetwork
  from org.modelio.archimate.metamodel.layers.technology.structure.active import TechnologyCollaboration
  from org.modelio.archimate.metamodel.layers.technology.structure.passive import Artifact
  from org.modelio.archimate.metamodel.layers.technology.structure.passive import TechnologyObject
  from org.modelio.archimate.metamodel.layers.physical.structure.active import DistributionNetwork
  from org.modelio.archimate.metamodel.layers.physical.structure.active import Equipment
  from org.modelio.archimate.metamodel.layers.physical.structure.active import Facility
  from org.modelio.archimate.metamodel.layers.physical.structure.passive import Material
  from org.modelio.archimate.metamodel.layers.strategy.structure import Resource
  from org.modelio.archimate.metamodel.layers.strategy.behavior import Capability
  from org.modelio.archimate.metamodel.layers.strategy.behavior import CourseOfAction
  from org.modelio.archimate.metamodel.visitors import IArchimateVisitor
  from org.modelio.archimate.metamodel.visitors import AbstractArchimateVisitor
  from org.modelio.archimate.metamodel.visitors import DefaultArchimateVisitor
  from org.modelio.archimate.metamodel.visitors import IAbstractArchimateVisitor
  from org.modelio.archimate.metamodel.visitors import IDefaultArchimateVisitor
  from org.modelio.archimate.metamodel.mmextensions.archimate import IArchimateModelFactory
if isFragmentDeployed("Analyst"):
  ''' imports of modelio.analyst.api '''
  from com.modeliosoft.modelio.analyst.model import IAnalystModel
  from com.modeliosoft.modelio.analyst.plugin import AnalystClassLoaderProvider
if isFragmentDeployed("Analyst"):
  ''' imports of implementation.api '''
  from org.modelio.metamodel.analyst import AnalystContainer
  from org.modelio.metamodel.analyst import AnalystElement
  from org.modelio.metamodel.analyst import AnalystItem
  from org.modelio.metamodel.analyst import AnalystProject
  from org.modelio.metamodel.analyst import AnalystPropertyTable
  from org.modelio.metamodel.analyst import BusinessRule
  from org.modelio.metamodel.analyst import BusinessRuleContainer
  from org.modelio.metamodel.analyst import Dictionary
  from org.modelio.metamodel.analyst import GenericAnalystContainer
  from org.modelio.metamodel.analyst import GenericAnalystElement
  from org.modelio.metamodel.analyst import Goal
  from org.modelio.metamodel.analyst import GoalContainer
  from org.modelio.metamodel.analyst import KPI
  from org.modelio.metamodel.analyst import KPIContainer
  from org.modelio.metamodel.analyst import Requirement
  from org.modelio.metamodel.analyst import RequirementContainer
  from org.modelio.metamodel.analyst import Risk
  from org.modelio.metamodel.analyst import RiskContainer
  from org.modelio.metamodel.analyst import Term
  from org.modelio.metamodel.analyst import Test
  from org.modelio.metamodel.analyst import TestContainer
  from org.modelio.metamodel import AnalystMetamodel
  from org.modelio.metamodel.visitors import IAnalystVisitor
  from org.modelio.metamodel.visitors import AbstractAnalystVisitor
  from org.modelio.metamodel.visitors import DefaultAnalystVisitor
  from org.modelio.metamodel.visitors import IAbstractAnalystVisitor
  from org.modelio.metamodel.visitors import IDefaultAnalystVisitor
  from org.modelio.metamodel.mmextensions.analyst.facilities import AnalystPropertiesHelper
  from org.modelio.metamodel.mmextensions.analyst import IAnalystModelFactory
if isFragmentDeployed("Uml"):
  ''' imports of implementation.api '''
if isFragmentDeployed("Bpmn"):
  ''' imports of bpmn_implementation.api '''
if isFragmentDeployed("Infrastructure"):
  ''' imports of infrastructure_impl.api '''
  from org.modelio.metamodel.uml.infrastructure import AbstractProject
  from org.modelio.metamodel.uml.infrastructure import AbstractResource
  from org.modelio.metamodel.uml.infrastructure import Dependency
  from org.modelio.metamodel.uml.infrastructure import Document
  from org.modelio.metamodel.uml.infrastructure import Element
  from org.modelio.metamodel.uml.infrastructure import ExternElement
  from org.modelio.metamodel.uml.infrastructure import ExternProcessor
  from org.modelio.metamodel.uml.infrastructure import IResourceHandle
  from org.modelio.metamodel.uml.infrastructure import MetaclassReference
  from org.modelio.metamodel.uml.infrastructure import MethodologicalLink
  from org.modelio.metamodel.uml.infrastructure import ModelElement
  from org.modelio.metamodel.uml.infrastructure import Note
  from org.modelio.metamodel.uml.infrastructure import NoteType
  from org.modelio.metamodel.uml.infrastructure import Profile
  from org.modelio.metamodel.uml.infrastructure import Resource
  from org.modelio.metamodel.uml.infrastructure import ResourceType
  from org.modelio.metamodel.uml.infrastructure import Stereotype
  from org.modelio.metamodel.uml.infrastructure import TagParameter
  from org.modelio.metamodel.uml.infrastructure import TagType
  from org.modelio.metamodel.uml.infrastructure import TaggedValue
  from org.modelio.metamodel.uml.infrastructure.matrix import MatrixDefinition
  from org.modelio.metamodel.uml.infrastructure.matrix import QueryDefinition
  from org.modelio.metamodel.uml.infrastructure.matrix import MatrixValueDefinition
  from org.modelio.metamodel.uml.infrastructure.properties import PropertyDefinition
  from org.modelio.metamodel.uml.infrastructure.properties import PropertyTableDefinition
  from org.modelio.metamodel.uml.infrastructure.properties import PropertyTable
  from org.modelio.metamodel.uml.infrastructure.properties import TypedPropertyTable
  from org.modelio.metamodel.uml.infrastructure.properties import LocalPropertyTable
  from org.modelio.metamodel.uml.infrastructure.properties import PropertyType
  from org.modelio.metamodel.uml.infrastructure.properties import EnumeratedPropertyType
  from org.modelio.metamodel.uml.infrastructure.properties import PropertyEnumerationLitteral
  from org.modelio.metamodel.uml.infrastructure.properties import PropertyBaseType
  from org.modelio.metamodel.uml.infrastructure.properties import DynamicPropertyDefinition
  from org.modelio.metamodel.mda import ModuleParameter
  from org.modelio.metamodel.mda import ModuleComponent
  from org.modelio.metamodel.mda import ModuleState
  from org.modelio.metamodel.mda import ModuleParameterType
  from org.modelio.metamodel.diagrams import AbstractDiagram
  from org.modelio.metamodel.diagrams import DiagramSet
  from org.modelio.metamodel.diagrams import GraphDiagram
  from org.modelio.metamodel import InfrastructureMetamodel
  from org.modelio.metamodel.visitors import IInfrastructureVisitor
  from org.modelio.metamodel.visitors import AbstractInfrastructureVisitor
  from org.modelio.metamodel.visitors import DefaultInfrastructureVisitor
  from org.modelio.metamodel.visitors import IDefaultInfrastructureVisitor
  from org.modelio.metamodel.visitors import IAbstractInfrastructureVisitor
  from org.modelio.metamodel.impact import ImpactProject
  from org.modelio.metamodel.impact import ImpactModel
  from org.modelio.metamodel.impact import ImpactLink
  from org.modelio.metamodel.impact import ImpactDiagram
  from org.modelio.metamodel.mmextensions.infrastructure import ElementNotUniqueException
  from org.modelio.metamodel.mmextensions.infrastructure import ExtensionNotFoundException
  from org.modelio.metamodel.mmextensions.infrastructure import IInfrastructureModelFactory
  from org.modelio.metamodel.mmextensions.infrastructure import IResourceBuilder
if isFragmentDeployed("Standard"):
  ''' imports of standard_implementation.api '''
  from org.modelio.metamodel.bpmn.processCollaboration import BpmnProcessType
  from org.modelio.metamodel.bpmn.processCollaboration import OptionalBoolean
  from org.modelio.metamodel.bpmn.processCollaboration import BpmnCollaboration
  from org.modelio.metamodel.bpmn.processCollaboration import BpmnLane
  from org.modelio.metamodel.bpmn.processCollaboration import BpmnLaneSet
  from org.modelio.metamodel.bpmn.processCollaboration import BpmnParticipant
  from org.modelio.metamodel.bpmn.processCollaboration import BpmnProcess
  from org.modelio.metamodel.bpmn.rootElements import BpmnAssociationDirection
  from org.modelio.metamodel.bpmn.rootElements import BpmnAssociation
  from org.modelio.metamodel.bpmn.rootElements import BpmnBaseElement
  from org.modelio.metamodel.bpmn.rootElements import BpmnArtifact
  from org.modelio.metamodel.bpmn.rootElements import BpmnFlowElement
  from org.modelio.metamodel.bpmn.rootElements import BpmnFlowNode
  from org.modelio.metamodel.bpmn.rootElements import BpmnGroup
  from org.modelio.metamodel.bpmn.rootElements import BpmnSharedDefinitions
  from org.modelio.metamodel.bpmn.rootElements import BpmnSharedElement
  from org.modelio.metamodel.bpmn.flows import BpmnMessage
  from org.modelio.metamodel.bpmn.flows import BpmnMessageFlow
  from org.modelio.metamodel.bpmn.flows import BpmnSequenceFlow
  from org.modelio.metamodel.bpmn.activities import AdHocOrdering
  from org.modelio.metamodel.bpmn.activities import MultiInstanceBehavior
  from org.modelio.metamodel.bpmn.activities import TransactionMethod
  from org.modelio.metamodel.bpmn.activities import BpmnActivity
  from org.modelio.metamodel.bpmn.activities import BpmnAdHocSubProcess
  from org.modelio.metamodel.bpmn.activities import BpmnBusinessRuleTask
  from org.modelio.metamodel.bpmn.activities import BpmnCallActivity
  from org.modelio.metamodel.bpmn.activities import BpmnComplexBehaviorDefinition
  from org.modelio.metamodel.bpmn.activities import BpmnLoopCharacteristics
  from org.modelio.metamodel.bpmn.activities import BpmnManualTask
  from org.modelio.metamodel.bpmn.activities import BpmnMultiInstanceLoopCharacteristics
  from org.modelio.metamodel.bpmn.activities import BpmnReceiveTask
  from org.modelio.metamodel.bpmn.activities import BpmnScriptTask
  from org.modelio.metamodel.bpmn.activities import BpmnSendTask
  from org.modelio.metamodel.bpmn.activities import BpmnServiceTask
  from org.modelio.metamodel.bpmn.activities import BpmnStandardLoopCharacteristics
  from org.modelio.metamodel.bpmn.activities import BpmnSubProcess
  from org.modelio.metamodel.bpmn.activities import BpmnTask
  from org.modelio.metamodel.bpmn.activities import BpmnTransaction
  from org.modelio.metamodel.bpmn.activities import BpmnUserTask
  from org.modelio.metamodel.bpmn.events import BpmnBoundaryEvent
  from org.modelio.metamodel.bpmn.events import BpmnCancelEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnCatchEvent
  from org.modelio.metamodel.bpmn.events import BpmnCompensateEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnConditionalEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnEndEvent
  from org.modelio.metamodel.bpmn.events import BpmnErrorEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnEscalationEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnEvent
  from org.modelio.metamodel.bpmn.events import BpmnEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnImplicitThrowEvent
  from org.modelio.metamodel.bpmn.events import BpmnIntermediateCatchEvent
  from org.modelio.metamodel.bpmn.events import BpmnIntermediateThrowEvent
  from org.modelio.metamodel.bpmn.events import BpmnLinkEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnMessageEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnSignalEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnStartEvent
  from org.modelio.metamodel.bpmn.events import BpmnTerminateEventDefinition
  from org.modelio.metamodel.bpmn.events import BpmnThrowEvent
  from org.modelio.metamodel.bpmn.events import BpmnTimerEventDefinition
  from org.modelio.metamodel.bpmn.gateways import BpmnEventBasedGatewayType
  from org.modelio.metamodel.bpmn.gateways import BpmnGatewayDirection
  from org.modelio.metamodel.bpmn.gateways import BpmnComplexGateway
  from org.modelio.metamodel.bpmn.gateways import BpmnEventBasedGateway
  from org.modelio.metamodel.bpmn.gateways import BpmnExclusiveGateway
  from org.modelio.metamodel.bpmn.gateways import BpmnGateway
  from org.modelio.metamodel.bpmn.gateways import BpmnInclusiveGateway
  from org.modelio.metamodel.bpmn.gateways import BpmnParallelGateway
  from org.modelio.metamodel.bpmn.objects import BpmnItemKind
  from org.modelio.metamodel.bpmn.objects import BpmnDataObject
  from org.modelio.metamodel.bpmn.objects import BpmnDataStore
  from org.modelio.metamodel.bpmn.objects import BpmnDataAssociation
  from org.modelio.metamodel.bpmn.objects import BpmnSequenceFlowDataAssociation
  from org.modelio.metamodel.bpmn.objects import BpmnDataOutput
  from org.modelio.metamodel.bpmn.objects import BpmnDataInput
  from org.modelio.metamodel.bpmn.objects import BpmnItemAwareElement
  from org.modelio.metamodel.bpmn.objects import BpmnItemDefinition
  from org.modelio.metamodel.bpmn.objects import BpmnDataState
  from org.modelio.metamodel.bpmn.resources import BpmnResource
  from org.modelio.metamodel.bpmn.resources import BpmnResourceParameter
  from org.modelio.metamodel.bpmn.resources import BpmnResourceRole
  from org.modelio.metamodel.bpmn.resources import BpmnResourceParameterBinding
  from org.modelio.metamodel.bpmn.bpmnDiagrams import BpmnProcessCollaborationDiagram
  from org.modelio.metamodel.bpmn.bpmnDiagrams import BpmnSubProcessDiagram
  from org.modelio.metamodel.bpmn.bpmnDiagrams import BpmnProcessDesignDiagram
  from org.modelio.metamodel.bpmn.bpmnDiagrams import BpmnCollaborationDiagram
  from org.modelio.metamodel.bpmn.bpmnService import BpmnOperation
  from org.modelio.metamodel.bpmn.bpmnService import BpmnInterface
  from org.modelio.metamodel.bpmn.bpmnService import BpmnEndPoint
  from org.modelio.metamodel.diagrams import ActivityDiagram
  from org.modelio.metamodel.diagrams import BehaviorDiagram
  from org.modelio.metamodel.diagrams import ClassDiagram
  from org.modelio.metamodel.diagrams import CommunicationDiagram
  from org.modelio.metamodel.diagrams import DeploymentDiagram
  from org.modelio.metamodel.diagrams import SequenceDiagram
  from org.modelio.metamodel.diagrams import StateMachineDiagram
  from org.modelio.metamodel.diagrams import StaticDiagram
  from org.modelio.metamodel.diagrams import UseCaseDiagram
  from org.modelio.metamodel.diagrams import ObjectDiagram
  from org.modelio.metamodel.diagrams import CompositeStructureDiagram
  from org.modelio.metamodel.mda import Project
  from org.modelio.metamodel.uml.infrastructure import Abstraction
  from org.modelio.metamodel.uml.infrastructure import Constraint
  from org.modelio.metamodel.uml.infrastructure import ModelTree
  from org.modelio.metamodel.uml.infrastructure import Substitution
  from org.modelio.metamodel.uml.infrastructure import Usage
  from org.modelio.metamodel.uml.infrastructure import UmlModelElement
  from org.modelio.metamodel.uml.statik import AggregationKind
  from org.modelio.metamodel.uml.statik import KindOfAccess
  from org.modelio.metamodel.uml.statik import MethodPassingMode
  from org.modelio.metamodel.uml.statik import PassingMode
  from org.modelio.metamodel.uml.statik import VisibilityMode
  from org.modelio.metamodel.uml.statik import Artifact
  from org.modelio.metamodel.uml.statik import AssociationEnd
  from org.modelio.metamodel.uml.statik import Attribute
  from org.modelio.metamodel.uml.statik import AttributeLink
  from org.modelio.metamodel.uml.statik import BindableInstance
  from org.modelio.metamodel.uml.statik import Binding
  from org.modelio.metamodel.uml.statik import Class
  from org.modelio.metamodel.uml.statik import ClassAssociation
  from org.modelio.metamodel.uml.statik import Classifier
  from org.modelio.metamodel.uml.statik import Collaboration
  from org.modelio.metamodel.uml.statik import CollaborationUse
  from org.modelio.metamodel.uml.statik import Component
  from org.modelio.metamodel.uml.statik import NaryConnector
  from org.modelio.metamodel.uml.statik import ConnectorEnd
  from org.modelio.metamodel.uml.statik import DataType
  from org.modelio.metamodel.uml.statik import ElementImport
  from org.modelio.metamodel.uml.statik import ElementRealization
  from org.modelio.metamodel.uml.statik import Enumeration
  from org.modelio.metamodel.uml.statik import EnumerationLiteral
  from org.modelio.metamodel.uml.statik import Feature
  from org.modelio.metamodel.uml.statik import GeneralClass
  from org.modelio.metamodel.uml.statik import Generalization
  from org.modelio.metamodel.uml.statik import Instance
  from org.modelio.metamodel.uml.statik import Interface
  from org.modelio.metamodel.uml.statik import InterfaceRealization
  from org.modelio.metamodel.uml.statik import LinkEnd
  from org.modelio.metamodel.uml.statik import Manifestation
  from org.modelio.metamodel.uml.statik import NameSpace
  from org.modelio.metamodel.uml.statik import Node
  from org.modelio.metamodel.uml.statik import Operation
  from org.modelio.metamodel.uml.statik import Package
  from org.modelio.metamodel.uml.statik import PackageImport
  from org.modelio.metamodel.uml.statik import PackageMerge
  from org.modelio.metamodel.uml.statik import Parameter
  from org.modelio.metamodel.uml.statik import Port
  from org.modelio.metamodel.uml.statik import ProvidedInterface
  from org.modelio.metamodel.uml.statik import RaisedException
  from org.modelio.metamodel.uml.statik import RequiredInterface
  from org.modelio.metamodel.uml.statik import TemplateBinding
  from org.modelio.metamodel.uml.statik import TemplateParameter
  from org.modelio.metamodel.uml.statik import TemplateParameterSubstitution
  from org.modelio.metamodel.uml.statik import StructuralFeature
  from org.modelio.metamodel.uml.statik import BehavioralFeature
  from org.modelio.metamodel.uml.statik import NaryAssociationEnd
  from org.modelio.metamodel.uml.statik import NaryAssociation
  from org.modelio.metamodel.uml.statik import NaryLink
  from org.modelio.metamodel.uml.statik import PortOrientation
  from org.modelio.metamodel.uml.statik import NaryLinkEnd
  from org.modelio.metamodel.uml.statik import NaryConnectorEnd
  from org.modelio.metamodel.uml.statik import Association
  from org.modelio.metamodel.uml.statik import Link
  from org.modelio.metamodel.uml.statik import Connector
  from org.modelio.metamodel.uml.statik import Navigability
  from org.modelio.metamodel.uml.statik import ComponentRealization
  from org.modelio.metamodel.uml.behavior.activityModel import DecisionNodeKind
  from org.modelio.metamodel.uml.behavior.activityModel import ExpansionKind
  from org.modelio.metamodel.uml.behavior.activityModel import ObjectFlowEffectKind
  from org.modelio.metamodel.uml.behavior.activityModel import ObjectNodeOrderingKind
  from org.modelio.metamodel.uml.behavior.activityModel import PinPassingMode
  from org.modelio.metamodel.uml.behavior.activityModel import AcceptCallEventAction
  from org.modelio.metamodel.uml.behavior.activityModel import AcceptChangeEventAction
  from org.modelio.metamodel.uml.behavior.activityModel import AcceptSignalAction
  from org.modelio.metamodel.uml.behavior.activityModel import AcceptTimeEventAction
  from org.modelio.metamodel.uml.behavior.activityModel import Activity
  from org.modelio.metamodel.uml.behavior.activityModel import ActivityAction
  from org.modelio.metamodel.uml.behavior.activityModel import ActivityEdge
  from org.modelio.metamodel.uml.behavior.activityModel import ActivityFinalNode
  from org.modelio.metamodel.uml.behavior.activityModel import ActivityGroup
  from org.modelio.metamodel.uml.behavior.activityModel import ActivityNode
  from org.modelio.metamodel.uml.behavior.activityModel import ActivityParameterNode
  from org.modelio.metamodel.uml.behavior.activityModel import ActivityPartition
  from org.modelio.metamodel.uml.behavior.activityModel import CallAction
  from org.modelio.metamodel.uml.behavior.activityModel import CallBehaviorAction
  from org.modelio.metamodel.uml.behavior.activityModel import CallOperationAction
  from org.modelio.metamodel.uml.behavior.activityModel import CentralBufferNode
  from org.modelio.metamodel.uml.behavior.activityModel import Clause
  from org.modelio.metamodel.uml.behavior.activityModel import ConditionalNode
  from org.modelio.metamodel.uml.behavior.activityModel import ControlFlow
  from org.modelio.metamodel.uml.behavior.activityModel import ControlNode
  from org.modelio.metamodel.uml.behavior.activityModel import DataStoreNode
  from org.modelio.metamodel.uml.behavior.activityModel import DecisionMergeNode
  from org.modelio.metamodel.uml.behavior.activityModel import ExceptionHandler
  from org.modelio.metamodel.uml.behavior.activityModel import ExpansionNode
  from org.modelio.metamodel.uml.behavior.activityModel import ExpansionRegion
  from org.modelio.metamodel.uml.behavior.activityModel import FinalNode
  from org.modelio.metamodel.uml.behavior.activityModel import FlowFinalNode
  from org.modelio.metamodel.uml.behavior.activityModel import ForkJoinNode
  from org.modelio.metamodel.uml.behavior.activityModel import InitialNode
  from org.modelio.metamodel.uml.behavior.activityModel import InputPin
  from org.modelio.metamodel.uml.behavior.activityModel import InstanceNode
  from org.modelio.metamodel.uml.behavior.activityModel import InterruptibleActivityRegion
  from org.modelio.metamodel.uml.behavior.activityModel import LoopNode
  from org.modelio.metamodel.uml.behavior.activityModel import MessageFlow
  from org.modelio.metamodel.uml.behavior.activityModel import ObjectFlow
  from org.modelio.metamodel.uml.behavior.activityModel import ObjectNode
  from org.modelio.metamodel.uml.behavior.activityModel import OpaqueAction
  from org.modelio.metamodel.uml.behavior.activityModel import OutputPin
  from org.modelio.metamodel.uml.behavior.activityModel import Pin
  from org.modelio.metamodel.uml.behavior.activityModel import SendSignalAction
  from org.modelio.metamodel.uml.behavior.activityModel import StructuredActivityNode
  from org.modelio.metamodel.uml.behavior.activityModel import ValuePin
  from org.modelio.metamodel.uml.behavior.commonBehaviors import ParameterEffectKind
  from org.modelio.metamodel.uml.behavior.commonBehaviors import EventType
  from org.modelio.metamodel.uml.behavior.commonBehaviors import Behavior
  from org.modelio.metamodel.uml.behavior.commonBehaviors import BehaviorParameter
  from org.modelio.metamodel.uml.behavior.commonBehaviors import OpaqueBehavior
  from org.modelio.metamodel.uml.behavior.commonBehaviors import Signal
  from org.modelio.metamodel.uml.behavior.commonBehaviors import Event
  from org.modelio.metamodel.uml.behavior.interactionModel import InteractionOperator
  from org.modelio.metamodel.uml.behavior.interactionModel import MessageKind
  from org.modelio.metamodel.uml.behavior.interactionModel import MessageSort
  from org.modelio.metamodel.uml.behavior.interactionModel import RelativeTime
  from org.modelio.metamodel.uml.behavior.interactionModel import CombinedFragment
  from org.modelio.metamodel.uml.behavior.interactionModel import DurationConstraint
  from org.modelio.metamodel.uml.behavior.interactionModel import ExecutionOccurenceSpecification
  from org.modelio.metamodel.uml.behavior.interactionModel import ExecutionSpecification
  from org.modelio.metamodel.uml.behavior.interactionModel import Gate
  from org.modelio.metamodel.uml.behavior.interactionModel import GeneralOrdering
  from org.modelio.metamodel.uml.behavior.interactionModel import Interaction
  from org.modelio.metamodel.uml.behavior.interactionModel import InteractionFragment
  from org.modelio.metamodel.uml.behavior.interactionModel import InteractionOperand
  from org.modelio.metamodel.uml.behavior.interactionModel import InteractionUse
  from org.modelio.metamodel.uml.behavior.interactionModel import Lifeline
  from org.modelio.metamodel.uml.behavior.interactionModel import Message
  from org.modelio.metamodel.uml.behavior.interactionModel import MessageEnd
  from org.modelio.metamodel.uml.behavior.interactionModel import OccurrenceSpecification
  from org.modelio.metamodel.uml.behavior.interactionModel import PartDecomposition
  from org.modelio.metamodel.uml.behavior.interactionModel import StateInvariant
  from org.modelio.metamodel.uml.behavior.interactionModel import TerminateSpecification
  from org.modelio.metamodel.uml.behavior.stateMachineModel import KindOfControl
  from org.modelio.metamodel.uml.behavior.stateMachineModel import KindOfStateMachine
  from org.modelio.metamodel.uml.behavior.stateMachineModel import PredefinedEventType
  from org.modelio.metamodel.uml.behavior.stateMachineModel import StateKind
  from org.modelio.metamodel.uml.behavior.stateMachineModel import AbstractPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import ChoicePseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import ConnectionPointReference
  from org.modelio.metamodel.uml.behavior.stateMachineModel import DeepHistoryPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import EntryPointPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import ExitPointPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import ForkPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import InitialPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import InternalTransition
  from org.modelio.metamodel.uml.behavior.stateMachineModel import JoinPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import JunctionPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import ShallowHistoryPseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import State
  from org.modelio.metamodel.uml.behavior.stateMachineModel import StateMachine
  from org.modelio.metamodel.uml.behavior.stateMachineModel import StateVertex
  from org.modelio.metamodel.uml.behavior.stateMachineModel import TerminatePseudoState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import Transition
  from org.modelio.metamodel.uml.behavior.stateMachineModel import FinalState
  from org.modelio.metamodel.uml.behavior.stateMachineModel import Region
  from org.modelio.metamodel.uml.behavior.usecaseModel import Actor
  from org.modelio.metamodel.uml.behavior.usecaseModel import UseCase
  from org.modelio.metamodel.uml.behavior.usecaseModel import UseCaseDependency
  from org.modelio.metamodel.uml.behavior.usecaseModel import ExtensionPoint
  from org.modelio.metamodel.uml.behavior.communicationModel import CommunicationInteraction
  from org.modelio.metamodel.uml.behavior.communicationModel import CommunicationNode
  from org.modelio.metamodel.uml.behavior.communicationModel import CommunicationMessage
  from org.modelio.metamodel.uml.behavior.communicationModel import CommunicationChannel
  from org.modelio.metamodel.uml.informationFlow import InformationFlow
  from org.modelio.metamodel.uml.informationFlow import InformationItem
  from org.modelio.metamodel.uml.informationFlow import DataFlow
  from org.modelio.metamodel.visitors import IModelVisitor
  from org.modelio.metamodel.visitors import AbstractModelVisitor
  from org.modelio.metamodel.visitors import DefaultModelVisitor
  from org.modelio.metamodel.visitors import IDefaultModelVisitor
  from org.modelio.metamodel.visitors import IAbstractModelVisitor
  from org.modelio.metamodel import StandardMetamodel
  from org.modelio.metamodel import PredefinedTypes
  from org.modelio.metamodel.mmextensions.standard.facilities import BrokenElementTester
  from org.modelio.metamodel.mmextensions.standard.facilities import CompositionInitializer
  from org.modelio.metamodel.mmextensions.standard.facilities import RelatedDiagramHelper
  from org.modelio.metamodel.mmextensions.standard.facilities.interaction import MessageSequencer
  from org.modelio.metamodel.mmextensions.standard.facilities.interaction import InteractionHelper
  from org.modelio.metamodel.mmextensions.standard.factory import IStandardModelFactory
  from org.modelio.metamodel.mmextensions.standard.services import IMModelServices
  from org.modelio.metamodel.mmextensions.standard.services import MModelServices
  from org.modelio.metamodel.mmextensions.standard.services import ExtensionCache
''' imports of API.api '''
from org.modelio.metamodel import Metamodel
from org.modelio.api.astyle import AStyle
from org.modelio.api.astyle import AStyleInterface
from org.modelio.api.modelio import Modelio
from org.modelio.api.modelio import IModelioContext
from org.modelio.api.modelio import IModelioServices
from org.modelio.api.modelio.audit import IAuditService
from org.modelio.api.modelio.diagram import ContributorCategory
from org.modelio.api.modelio.diagram import DefaultDiagramCustomizer
from org.modelio.api.modelio.diagram import IDGDynamicDecorator
from org.modelio.api.modelio.diagram import IDiagramCustomizer
from org.modelio.api.modelio.diagram import IDiagramDrawing
from org.modelio.api.modelio.diagram import IDiagramGraphic
from org.modelio.api.modelio.diagram import IDiagramGraphicFactory
from org.modelio.api.modelio.diagram import IDiagramHandle
from org.modelio.api.modelio.diagram import IDiagramLink
from org.modelio.api.modelio.diagram import IDiagramNode
from org.modelio.api.modelio.diagram import IDiagramService
from org.modelio.api.modelio.diagram import ILinkPath
from org.modelio.api.modelio.diagram import InvalidDestinationPointException
from org.modelio.api.modelio.diagram import InvalidPointsPathException
from org.modelio.api.modelio.diagram import InvalidSourcePointException
from org.modelio.api.modelio.diagram.autodiagram import IAutoDiagramFactory
from org.modelio.api.modelio.diagram.autodiagram import IDiagramCreator
from org.modelio.api.modelio.diagram.dg import IDiagramDG
from org.modelio.api.modelio.diagram.dg import IDiagramLayer
from org.modelio.api.modelio.diagram.dg import IDiagramElementsLayer
from org.modelio.api.modelio.diagram.dg import IDiagramDrawingsLayer
from org.modelio.api.modelio.diagram.style import IStyleHandle
from org.modelio.api.modelio.diagram.tools import DefaultAttachedBoxTool
from org.modelio.api.modelio.diagram.tools import DefaultBoxTool
from org.modelio.api.modelio.diagram.tools import DefaultLinkTool
from org.modelio.api.modelio.diagram.tools import DefaultMultiLinkTool
from org.modelio.api.modelio.diagram.tools import IAttachedBoxTool
from org.modelio.api.modelio.diagram.tools import IBoxTool
from org.modelio.api.modelio.diagram.tools import IDiagramTool
from org.modelio.api.modelio.diagram.tools import ILinkTool
from org.modelio.api.modelio.diagram.tools import IMultiLinkTool
from org.modelio.api.modelio.diagram.tools import DefaultDiagramTool
from org.modelio.api.modelio.diagram.tools import PaletteEntry
from org.modelio.api.modelio.diagram.tools.standard import GenericAttachedBoxTool
from org.modelio.api.modelio.diagram.tools.standard import GenericBoxTool
from org.modelio.api.modelio.diagram.tools.standard import GenericLinkTool
from org.modelio.api.modelio.diagram.tools.standard import GenericMultiLinkTool
from org.modelio.api.modelio.diagram import IDiagramDrawingNode
from org.modelio.api.modelio.diagram import IDiagramDrawingLink
from org.modelio.api.modelio.editor import EditorType
from org.modelio.api.modelio.editor import IEditionService
from org.modelio.api.modelio.editor import IExternDocumentChangeListener
from org.modelio.api.modelio.editor import IMDAEditorListener
from org.modelio.api.modelio.editor import IMDATextEditor
from org.modelio.api.modelio.exchange import IExchangeService
from org.modelio.api.modelio.exchange import XmiException
from org.modelio.api.modelio.exchange import XmiExportConfiguration
from org.modelio.api.modelio.exchange import XmiImportConfiguration
from org.modelio.api.modelio.mc import AbstractModelComponentContributor
from org.modelio.api.modelio.mc import DefaultModelComponentContributor
from org.modelio.api.modelio.mc import IModelComponentDescriptor
from org.modelio.api.modelio.mc import IModelComponentService
from org.modelio.api.modelio.meta import IMetamodelService
from org.modelio.api.modelio.model import IDefaultNameService
from org.modelio.api.modelio.model import IImageService
from org.modelio.api.modelio.model import IMetamodelExtensions
from org.modelio.api.modelio.model import IModelManipulationService
from org.modelio.api.modelio.model import IModelingSession
from org.modelio.api.modelio.model import ITransaction
from org.modelio.api.modelio.model import IUMLTypes
from org.modelio.api.modelio.model import IUmlModel
from org.modelio.api.modelio.model import InvalidPathException
from org.modelio.api.modelio.model import InvalidTransactionException
from org.modelio.api.modelio.model import InvalidUuidException
from org.modelio.api.modelio.model import PropertyConverter
from org.modelio.api.modelio.model.event import IElementDeletedEvent
from org.modelio.api.modelio.model.event import IElementMovedEvent
from org.modelio.api.modelio.model.event import IModelChangeEvent
from org.modelio.api.modelio.model.event import IModelChangeHandler
from org.modelio.api.modelio.model.event import IModelChangeListener
from org.modelio.api.modelio.model.event import IStatusChangeEvent
from org.modelio.api.modelio.model.event import IStatusChangeListener
from org.modelio.api.modelio.model.scope import ElementScope
from org.modelio.api.modelio.model.scope import StereotypeSpecReader
from org.modelio.api.modelio.module import IModuleService
from org.modelio.api.modelio.navigation import INavigationListener
from org.modelio.api.modelio.navigation import INavigationService
from org.modelio.api.modelio.pattern import IPatternService
from org.modelio.api.modelio.picking import IPickingService
from org.modelio.api.modelio.picking import IPickingProvider
from org.modelio.api.modelio.picking import IPickingClient
from org.modelio.api.modelio.picking import IPickingSession
from org.modelio.api.modelio import IModelioServicesRegistry
from org.modelio.api.module import AbstractJavaModule
from org.modelio.api.module import IModule
from org.modelio.api.module import IPeerModule
from org.modelio.api.module.command import ActionLocation
from org.modelio.api.module.command import DefaultModuleCommandHandler
from org.modelio.api.module.command import DefaultModuleAction
from org.modelio.api.module.command import IModuleAction
from org.modelio.api.module.command import IModuleCommandHandler
from org.modelio.api.module.command.standard import ApplyPatternStandardHandler
from org.modelio.api.module.command.standard import DiagramCreationStandardHandler
from org.modelio.api.module.command.standard import ElementCreationStandardHandler
from org.modelio.api.module.command.standard import RunJythonScriptBasicHandler
from org.modelio.api.module.command.standard import RunJythonScriptStandardHandler
from org.modelio.api.module.context import IModuleContext
from org.modelio.api.module.context.configuration import IConfigParamValidator
from org.modelio.api.module.context.configuration import IModuleAPIConfiguration
from org.modelio.api.module.context.configuration import IModuleUserConfiguration
from org.modelio.api.module.context.i18n import I18nSupport
from org.modelio.api.module.context.log import ILogService
from org.modelio.api.module.context.project import IProjectStructure
from org.modelio.api.module.context.project import IFragmentStructure
from org.modelio.api.module.context.project import IModuleStructure
from org.modelio.api.module.license import ILicenseInfos
from org.modelio.api.module.lifecycle import IModuleLifeCycleHandler
from org.modelio.api.module.lifecycle import DefaultModuleLifeCycleHandler
from org.modelio.api.module.lifecycle import ModuleException
from org.modelio.api.module.mda import IMdaExpert
from org.modelio.api.module.parameter import IParameterEditionModel
from org.modelio.api.module.parameter import IParameterGroupModel
from org.modelio.api.module.parameter import IParameterModel
from org.modelio.api.module.parameter.impl import BoolParameterModel
from org.modelio.api.module.parameter.impl import ColorParameterModel
from org.modelio.api.module.parameter.impl import DirectoryParameterModel
from org.modelio.api.module.parameter.impl import EnumParameterModel
from org.modelio.api.module.parameter.impl import FileParameterModel
from org.modelio.api.module.parameter.impl import IntParameterModel
from org.modelio.api.module.parameter.impl import ParameterGroupModel
from org.modelio.api.module.parameter.impl import ParameterModel
from org.modelio.api.module.parameter.impl import ParametersEditionModel
from org.modelio.api.module.parameter.impl import PasswordParameterModel
from org.modelio.api.module.parameter.impl import StringParameterModel
from org.modelio.api.module.parameter import ModuleParameterType
from org.modelio.api.module.propertiesPage import AbstractModulePropertyPage
from org.modelio.api.module.propertiesPage import IModulePropertyPage
from org.modelio.api.module.propertiesPage import IModulePropertyTable
from org.modelio.api.module.propertiesPage import IModulePropertyPanel
from org.modelio.api.module.propertiesPage import IModulePropertyCustomPanel
from org.modelio.api.module.propertiesPage import ElementFormPropertyPanel
from org.modelio.api.module.script import IScriptService
from org.modelio.api.module.contributor import IWizardContributor
from org.modelio.api.module.contributor import AbstractWizardContributor
from org.modelio.api.module.contributor.diagramcreation import IDiagramWizardContributor
from org.modelio.api.module.contributor.diagramcreation import AbstractDiagramWizardContributor
from org.modelio.api.module.contributor.diagramcreation.standard import GenericDiagramWizardContributor
from org.modelio.api.module.contributor import ElementDescriptor
from org.modelio.api.plugin import Api
from org.modelio.api.ui import ModelioDialog
from org.modelio.api.ui import ModelioWizardDialog
from org.modelio.api.ui.contributor import DefaultWizardPreviewPanel
from org.modelio.api.ui.contributor import BrowserDialog
from org.modelio.api.ui.dnd import IEditorDropClient
from org.modelio.api.ui.dnd import EditorDropListener
from org.modelio.api.ui.dnd import ModelElementTransfer
from org.modelio.api.ui.form.fields import AbstractField
from org.modelio.api.ui.form.fields import BooleanField
from org.modelio.api.ui.form.fields import DateField
from org.modelio.api.ui.form.fields import ElementField
from org.modelio.api.ui.form.fields import EnumField
from org.modelio.api.ui.form.fields import HtmlTextField
from org.modelio.api.ui.form.fields import IField
from org.modelio.api.ui.form.fields import MultipleElementField
from org.modelio.api.ui.form.fields import NoteField
from org.modelio.api.ui.form.fields import RichTextField
from org.modelio.api.ui.form.fields import StringField
from org.modelio.api.ui.form.fields import TextField
from org.modelio.api.ui.form.fields import TimeField
from org.modelio.api.ui.form.models import AbstractTagFieldData
from org.modelio.api.ui.form.models import BooleanTagFieldData
from org.modelio.api.ui.form.models import DependencyListFieldData
from org.modelio.api.ui.form.models import ICandidateProvider
from org.modelio.api.ui.form.models import IFormFieldData
from org.modelio.api.ui.form.models import IFormFieldType
from org.modelio.api.ui.form.models import MAttributeFieldData
from org.modelio.api.ui.form.models import NoteFieldData
from org.modelio.api.ui.form.models import PropertyFieldData
from org.modelio.api.ui.form.models import StringTagFieldData
from org.modelio.api.ui.form import AbstractFieldFactory
from org.modelio.api.ui.form import FormFieldPage
from org.modelio.api.ui.form import IFieldFactory
from org.modelio.api.ui.form import ElementFormPanel
from org.modelio.api.ui.labelprovider import ElementLabelProvider
from org.modelio.api.ui.text import IElementChangeListener
from org.modelio.api.ui.text import IElementFilter
from org.modelio.api.ui.text import ResultsProposalPopup
from org.modelio.api.ui.text import TextWrapperForIElement
from org.modelio.api.ui.swt import IUiToolkit
from org.modelio.api.ui.swt.metaclassselect import IMetaclassSelector
from org.modelio.api.ui.swt import SelectionHelper

