// Disable all captions for figures.
:!figure-caption:

= Le cycle de vie d'un composant de modèle

=== Le cycle de vie d'un composant de modèle

Le cycle de vie d'un composant de modèle peut être divisé en trois phases distinctes :

1.  La <<Modeler-_modeler_local_libraries_model_components_development.adoc#,phase de développement>>, pendant laquelle le développeur prépare un composant de modèle en vue de son packaging. Cette phase inclut la construction du modèle UML et la création et la définition du futur composant de modèle lui-même, ainsi que la modélisation de ses dépendances à d'autres composants de modèle.
2.  La <<Modeler-_modeler_local_libraries_model_components_development.adoc#,phase de packaging>>, pendant laquelle le composant de modèle est véritablement construit par le développeur. Cette phase comprend la définition des informations de packaging, et la création d'un fichier de composant de modèle unique dont l'extension est ".ramc".
3.  La <<Modeler-_modeler_local_libraries_model_components_deployment.adoc#,phase de déploiement>>, durant laquelle le composant de modèle est déployé sur un projet par un utilisateur. Si des erreurs de déploiement sont rencontrées, elles peuvent être corrigées et le processus de déploiement relancé.

[[Les-versions-dun-composant-de-modèle-et-les-dépendances-entre-composants-de-modèle]]

[[les-versions-dun-composant-de-modèle-et-les-dépendances-entre-composants-de-modèle]]
=== Les versions d'un composant de modèle et les dépendances entre composants de modèle

Lorsqu'un composant de modèle est développé, un numéro de version lui est assigné. Ce numéro de version peut être incrémenté à chaque fois que le composant de modèle est repackagé (que ce soit à la suite de modifications effectuées ou lors des livraisons plannifiées).

Les dépendances qui existent entre les composants de modèle Modelio sont des dépendances strictes. Cela signifie qu'un composant de modèle dépend d'une version précise d'un autre composant de modèle. Cette version doit être respectée lors du déploiement du composant de modèle sur un projet.

Imaginons par exemple que nous avons deux composants de modèle, "A" et "B", tous les deux en version 1.0.0. Si la version 1.0.0 du composant de modèle "B" dépend de la version 1.0.0 du composant de modèle "A", et si la version 1.0.0 du composant de modèle "B" doit être déployée sur un projet, il faut suivre les étapes suivantes :

* Déployer d'abord la version 1.0.0 du composant de modèle "A".
* Déployer ensuite la version 1.0.0 du composant de modèle "B".

Imaginons maintenant que le composant de modèle "A" est modifié et repackagé avec un nouveau numéro de version 2.0.0. Nous voulons toujours déployer les composants de modèle "A" et "B". Voici les étapes à suivre :

* Tout d'abord, la dépendance d'origine entre le composant de modèle "B" et la version 1.0.0 du composant de modèle "A" doit être détruite.
* Ensuite, une nouvelle dépendance doit être créée entre le composant de modèle "B" et la version 2.0.0 du composant de modèle "A".
* Le composant de modèle "A" doit alors être repackagé et son numéro de version incrémenté.
* La version 2.0.0 du composant de modèle "A" peut désormais être déployé dans un projet, suivie de la nouvelle version du composant de modèle "B".


