// Disable all captions for figures.
:!figure-caption:
// Path to the stylesheet files
:stylesdir: .




= Couverture d'UML2




===== Introduction

Le service d'import / export XMI de Modelio a pour vocation de permettre l'import et l'export de la totalité des éléments de modèle.

A l'heure actuelle, seule une partie des éléments définis dans le métamodèle UML2 est gérée. La couverture est détaillée ci-après.

Par ailleurs, les imports / exports peuvent être incomplets à cause des différences qui existent entre les méta-modèles UML2 et Modelio.




===== Eléments des diagrammes statiques

*Diagrammes de classes*

Les éléments des diagrammes de classes sont traités en intégralité.

*Diagrammes d'objets*

Les éléments des diagrammes d'objets sont traités en intégralité.

*Diagrammes de composants*

Les éléments des diagrammes de composants sont traités en intégralité.

*Diagrammes de déploiement*

Les éléments des diagrammes de déploiement sont traités en intégralité.

*Diagrammes de packages*

Les éléments des diagrammes de packages sont traités en intégralité.

*Diagrammes de structure composite*

Les éléments des diagrammes de structures composites sont traités en intégralité.




===== Eléments des diagrammes de comportement

*Diagrammes de cas d'utilisation*

Les éléments des diagrammes de cas d'utilisation sont traités en intégralité.

*Diagrammes d'états*

Les éléments des diagrammes d'états sont traités en intégralité.

*Diagrammes d'activités*

Les éléments des diagrammes d'activités sont traités en intégralité.




===== Eléments des diagrammes dynamiques

*Diagrammes de séquence*

Les éléments des diagrammes de séquence sont traités en intégralité.

*Diagrammes de communication*

Les éléments des diagrammes de communication ne sont pas encore gérés.

*Diagrammes de timing*

Les éléments des diagrammes de timing ne sont pas gérés par Modelio.




===== Constructions auxiliaires

Les éléments de type " Template " sont traités en intégralité.




===== Profils

Les profils peuvent être importés sous Modelio à condition d'être définis dans un module. Ainsi les profils UML doivent être importés sous un module via la commande XMI dédiée : "<<Xmi_importing_profile.adoc#,Import de profil>>".

Les profils peuvent également être exportés via la commande XMI dédiée : "<<Xmi_exporting_profile.adoc#,Export de profil>>".




===== L'option de compatibilité Modelio

En activant <<Xmi_config.adoc#,l'option "Ajout des annotations Modelio">>, il est possible d'exporter et de réimporter des notes avec leur type associé. Si cette option n'a pas été activée, le type des notes sera perdu (restriction UML2). Par défaut, les notes importées sont de type "comment".

*Note :* Certaines métaclasses définissent des notions uniquement présentes dans UML2 ou dans Modelio. Celles-ci ne pourront pas être importées ou exportées.

Exemples : Dans les diagrammes de séquence, les "Continuation" n'existent pas dans Modelio et ne pourront donc pas être importés. Par ailleurs, les "ConsiderIgnoreFragment" seront importés en tant que simple "CombinedFragment".


