// Disable all captions for figures.
:!figure-caption:
// Path to the stylesheet files
:stylesdir: .

= Copyright

Copyright © 2020 Communauté Modelio.org — Tous droits réservés.

Ce programme est un logiciel libre ; vous pouvez le redistribuer ou le modifier suivant les termes de la "GNU General Public License" telle que publiée par la Free Software Foundation : soit la version 3 de cette licence, soit (à votre gré) toute version ultérieure.

Ce programme est distribué dans l'espoir qu'il vous sera utile, mais SANS AUCUNE GARANTIE : sans même la garantie implicite de COMMERCIALISABILITÉ ni d'ADÉQUATION À UN OBJECTIF PARTICULIER. Consultez la Licence Générale Publique GNU pour plus de détails.

Vous devriez avoir reçu une copie de la Licence Générale Publique GNU avec ce programme ; si ce n'est pas le cas, consultez : http://www.gnu.org/licenses/.

Ce produit inclus un logiciel développé par Apache Software Foundation http://www.apache.org/.

UML et OMG sont des marques déposées de Object Management Group. Tous les autres noms de produits ou de sociétés mentionnés sont des marques déposées appartenant à leurs propriétaires respectifs.


