// Disable all captions for figures.
:!figure-caption:
// Path to the stylesheet files
:stylesdir: .

[[R3120]]

[[r3120]]
= R3120

[[Résumé]]

[[résumé]]
===== Résumé

Un _LinkThrowEvent_ doit toujours être relié à un _LinkCatchEvent_.

[[Détails]]

[[détails]]
===== Détails

Les événements _BPMN Link_ facilitent la création de diagrammes BPMN en permettant de remplacer un flux de séquence _«qui serait difficile à router dans le diagramme»_ par une construction de type «goto / étiquette».

Dans cette construction, le *LinkThrowEvent* est similaire à un appel "goto" et le *LinkCatchEvent* associé est _"l'étiquette"_ à laquelle le flux est est transféré.

Pour que cette construction fonctionne et ait un sens, il est indispensable qu'un _LinkThrowEvent_ soit systématiquement associé à un _LinkCatchEvent_. La règle R3120 vérifie précisément ce point, en signalant comme _en défaut_ les événements de type _Link event_ non appairés.

De manière symétrique, la règle signale également les événements _LinkCatchEvent_ qui ne sont pas associés à au moins un _LinkThrowEvent_.

[[Conseils]]

[[conseils]]
===== Conseils

La correction à apporter est assez simple:

* soit associer le _Link event_ solitaire à un autre _Link event_, le cas échéant en créant cet autre événement.
* soit supprimer l'événement solitaire qui viole la règle dés lors que cet événement n'est plus utile et ne joue plus aucun role dans le processus.

[[A-propos-des-événements-de-lien]]

[[a-propos-des-événements-de-lien]]
A propos des événements de lien:

Les événements _Link event_ sont utiles lorsque:

* un processus ne s'affiche que sur plusieurs «pages» d'un diagramme compte-tenu de sa taille (processus non entièrement visible à l'écran). Dans ce cas, l'utilisation de paires _LinkThrowEvent/LinkCatchEvent_ peut aider à indiquer à l'utilisateur où se poursuit le déroulement du processus.
* un _SequenceFlow_ est difficile à acheminer de sa source vers sa cible sans encombrer le diagramme par un chemin long et tortueux. Dans de telles situations, une paire _LinkThrowEvent/LinkCatchEvent_ est généralement une solution élégante.

Le concepteur de BPMN doit cependant garder à l'esprit que, bien que utile et même parfois inévitable, l'utilisation d'une paire _LinkThrowEvent/LinkCatchEvent_ crée defacto une rupture dans le flux du processus. Il faut donc limiter l'utilisation de cette technique aux cas où les bénéfices l'emportent sur cet inconvénient.

[[Goodies]]

[[goodies]]
Goodies:

* les événements de type _Link event_ ont un nom dans Modelio qui peut être affiché dans le diagramme. Afficher le nom facilite grandement l'identification de la paire _LinkThrowEvent/LinkCatchEvent_ à condition que *le même nom soit utilisé* pour les deux nœuds de la paire. Ceci est la pratique recommandée par Modelio.
* la règle <<Modeler_audit_rules_R3200.adoc#,R3200>> renforce la pratique de nommage recommandée ci-dessus en surveillant les noms dans les paires _LinkThrowEvent/LinkCatchEvent_
* la sélection d'un nœud de type _Link event_ dans un diagramme met en évidence (highlighting) les nœuds appairés correspondants.

[[A-propos-de-la-règle]]

[[a-propos-de-la-règle]]
A propos de la règle:

* notre recommandation est de garder la règle R3120 activée et de ne jamais la désactiver complètement. La raison est qu'un _LinkThrowEvent/LinkCatchEvent_ solitaire (ie non appairé) brise en pratique le flux du processus, ce qui n'est jamais souhaitable.
* la gravité de la règle peut être réduite à «warning» ou «tip» pendant les phases initiales de conception, lorsque la définition en cours du processus le rend très instable. Dans de telles phases de conception, les erreurs signalées ne sont pas toujours pertinentes. Cependant, lors des phases de maintenance, notre recommandation est d'augmenter la gravité de la règle en «Erreur» car alors, toute rupture dans déroulement du processus due à des _Link event_ dé-appairés doit être immédiatement détectée et signalée comme une erreur nécessitant une correction.


