// Disable all captions for figures.
:!figure-caption:
// Path to the stylesheet files
:stylesdir: .




= R3200




===== Résumé

Un _LinkThrowEvent_ doit avoir le même nom que le _LinkCatchEvent_ auquel il est relié.




===== Détails

L'association d'un _LinkThrowEvent_ et d'un _LinkCatchEvent_ est une technique de modélisation dans BPMN qui aide à simplifier les diagrammes lorqu'ils sont complexes et denses et à augmenter la lisibilité.

Cette technique est comparable à un "Goto / Label" dans un langage de programmation. Pour de plus amples détails sur les paires _LinkThrowEvent/LinkCatchEvent_ dans BPMN, lire la page relative à la règle <<Modeler_audit_rules_R3120.adoc#,R3120>>.

Le gain de lisibilité attendu est conditionné par l'utilisation d'un nommage unique pour les nœuds de type _Link event_ associés entre eux.

La règle R3200 veille précisément à ce que les noms des _LinkThrowEvent/LinkCatchEvent_ associés soient les mêmes.




===== Conseils

La résolution de la règle R3200 est simple, il suffit de renommer l'un des événements _throw_ ou _catch_ afin que son nom corresponde à celui de son événement associé.

Afin de faciliter l'identification des couples _LinkThrowEvent/LinkCatchEvent_ dans un diagramme, Modelio les met en évidence (en affichant la liaison) dés que l'un d'entre eux est sélectionné dans le diagramme.


