// Disable all captions for figures.
:!figure-caption:
// Path to the stylesheet files
:stylesdir: .

[[Copyright-agreement]]

[[copyright-agreement]]
= Copyright agreement

© Copyright Modelio.org community and others 2020. +
All rights reserved. Visit https://www.modelio.org

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your choice) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.

This product includes software developed by the Apache Software Foundation (http://www.apache.org/).

ML and OMG are registered trademarks of the Object Management Group. All other company or product names are trademarks or registered trademarks of their respective owners.


