/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ParticipantBandKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParticipantBandKind">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="top_initiating"/>
 * &lt;enumeration value="middle_initiating"/>
 * &lt;enumeration value="bottom_initiating"/>
 * &lt;enumeration value="top_non_initiating"/>
 * &lt;enumeration value="middle_non_initiating"/>
 * &lt;enumeration value="bottom_non_initiating"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("31db4490-6aa3-4a44-b040-653c5f45bd5f")
@XmlType(name = "ParticipantBandKind", namespace = "http://www.omg.org/spec/BPMN/20100524/DI")
@XmlEnum
public enum ParticipantBandKind {
    @objid ("c595a83e-986d-4d83-ad55-64a11a09e810")
    @XmlEnumValue("top_initiating")
    TOP_INITIATING("top_initiating"),
    @objid ("bc02a7e2-f599-4246-9967-0d6c16d86e26")
    @XmlEnumValue("middle_initiating")
    MIDDLE_INITIATING("middle_initiating"),
    @objid ("68177c53-18b1-42c5-9f2c-ebd76bb84bc2")
    @XmlEnumValue("bottom_initiating")
    BOTTOM_INITIATING("bottom_initiating"),
    @objid ("c8c7f9b4-6668-434e-8e9e-4f3c434cb5e9")
    @XmlEnumValue("top_non_initiating")
    TOP_NON_INITIATING("top_non_initiating"),
    @objid ("3f9da25f-7247-406d-ac89-47c9cdbca016")
    @XmlEnumValue("middle_non_initiating")
    MIDDLE_NON_INITIATING("middle_non_initiating"),
    @objid ("45a0a67a-176b-49f4-9ed9-48cc2f393d0c")
    @XmlEnumValue("bottom_non_initiating")
    BOTTOM_NON_INITIATING("bottom_non_initiating");

    @objid ("24abfa9d-fb12-4422-adf3-926d960d9def")
    private final String value;

    @objid ("4604aef5-7e27-42f6-bdf0-174eb460c50f")
     ParticipantBandKind(String v) {
        this.value = v;
    }

    @objid ("b94c866f-568f-4345-bce6-760335f8f71a")
    public String value() {
        return this.value;
    }

    @objid ("bd203c38-be32-471a-8a3d-99ca83906e96")
    public static ParticipantBandKind fromValue(String v) {
        for (ParticipantBandKind c: ParticipantBandKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
        
    }

}
