/* 
 * Copyright 2013-2018 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tAdHocSubProcess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAdHocSubProcess">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tSubProcess">
 * &lt;sequence>
 * &lt;element name="completionCondition" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="cancelRemainingInstances" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 * &lt;attribute name="ordering" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tAdHocOrdering" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("066e0a76-59d5-4fc8-974d-4f2bf42eb712")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAdHocSubProcess", propOrder = {
    "completionCondition"
})
public class TAdHocSubProcess extends TSubProcess {
    @objid ("55eeb0f8-9f58-44ff-a9b2-258451a781fd")
    @XmlAttribute(name = "cancelRemainingInstances")
    protected Boolean cancelRemainingInstances;

    @objid ("d0175b06-f5f8-479e-9449-ae2d123c3a6f")
    @XmlAttribute(name = "ordering")
    protected TAdHocOrdering ordering;

    @objid ("8cc21406-33d5-4b24-8c7d-ccf8a20cb450")
    protected TExpression completionCondition;

    /**
     * Gets the value of the completionCondition property.
     * @return
     * possible object is
     * {@link TExpression }
     */
    @objid ("21e92dfc-4385-4bd1-a4df-2ee5f5a6ec4b")
    public TExpression getCompletionCondition() {
        return this.completionCondition;
    }

    /**
     * Sets the value of the completionCondition property.
     * @param value allowed object is
     * {@link TExpression }
     */
    @objid ("45fafe44-1d50-4e30-bcef-151c3fd6d107")
    public void setCompletionCondition(TExpression value) {
        this.completionCondition = value;
    }

    /**
     * Gets the value of the cancelRemainingInstances property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    @objid ("6e641525-6fe8-445e-97fb-324eec260dd7")
    public boolean isCancelRemainingInstances() {
        if (this.cancelRemainingInstances == null) {
            return true;
        } else {
            return this.cancelRemainingInstances;
        }
    }

    /**
     * Sets the value of the cancelRemainingInstances property.
     * @param value allowed object is
     * {@link Boolean }
     */
    @objid ("75b4be5a-7fc7-4972-a466-1eaadf6cca5f")
    public void setCancelRemainingInstances(Boolean value) {
        this.cancelRemainingInstances = value;
    }

    /**
     * Gets the value of the ordering property.
     * @return
     * possible object is
     * {@link TAdHocOrdering }
     */
    @objid ("1a097634-8c15-497e-9ce9-bb5de3df5dad")
    public TAdHocOrdering getOrdering() {
        return this.ordering;
    }

    /**
     * Sets the value of the ordering property.
     * @param value allowed object is
     * {@link TAdHocOrdering }
     */
    @objid ("3b85617c-f637-4fb3-8478-888106421a3b")
    public void setOrdering(TAdHocOrdering value) {
        this.ordering = value;
    }

}
