/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for tAdHocOrdering.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tAdHocOrdering">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Parallel"/>
 * &lt;enumeration value="Sequential"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("0a08836a-207f-4c5d-a993-58fc95cfd3cd")
@XmlType(name = "tAdHocOrdering")
@XmlEnum
public enum TAdHocOrdering {
    @objid ("778dbc95-a0eb-4c8c-a578-a2380730e80e")
    @XmlEnumValue("Parallel")
    PARALLEL("Parallel"),
    @objid ("c43bd704-92d8-475d-a39d-7b5e6f1dbe9a")
    @XmlEnumValue("Sequential")
    SEQUENTIAL("Sequential");

    @objid ("60536696-dab5-4f95-9568-c8f7ad62c004")
    private final String value;

    @objid ("b05f068c-24ea-463f-8275-e894a9f8523d")
     TAdHocOrdering(String v) {
        this.value = v;
    }

    @objid ("53ee85fc-4f95-46c9-897f-2f4f06f2a5ff")
    public String value() {
        return this.value;
    }

    @objid ("13edb721-4dca-4a06-ada7-cb29466b6c06")
    public static TAdHocOrdering fromValue(String v) {
        for (TAdHocOrdering c: TAdHocOrdering.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
        
    }

}
