/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tAssignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAssignment">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tBaseElement">
 * &lt;sequence>
 * &lt;element name="from" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression"/>
 * &lt;element name="to" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression"/>
 * &lt;/sequence>
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("c9cbddf2-de0b-4e6e-ad2d-63e04b51b7d2")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAssignment", propOrder = {
    "from",
    "to"
})
public class TAssignment extends TBaseElement {
    @objid ("98650d16-c548-4c59-9826-eb39626dd5a4")
    @XmlElement(required = true)
    protected TExpression from;

    @objid ("59ab1491-e6ad-4345-bd9d-1865f63b07af")
    @XmlElement(required = true)
    protected TExpression to;

    /**
     * Gets the value of the from property.
     * @return
     * possible object is
     * {@link TExpression }
     */
    @objid ("63c1a7aa-dfb1-4e17-8dbe-84995205375f")
    public TExpression getFrom() {
        return this.from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value allowed object is
     * {@link TExpression }
     */
    @objid ("0ae3188e-3174-4092-b403-1c196e941ecf")
    public void setFrom(TExpression value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * @return
     * possible object is
     * {@link TExpression }
     */
    @objid ("e6088145-b2a3-446f-812d-f8291a90fc6d")
    public TExpression getTo() {
        return this.to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value allowed object is
     * {@link TExpression }
     */
    @objid ("a69d681f-098f-4174-a724-8b953630098a")
    public void setTo(TExpression value) {
        this.to = value;
    }

}
