/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * <p>Java class for tBaseElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tBaseElement">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}documentation" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}extensionElements" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("6eee2c4c-56e8-4dab-80d5-1cfb6908cb63")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tBaseElement", propOrder = {
    "documentation",
    "extensionElements"
})
@XmlSeeAlso({
    TConversationAssociation.class,
    TInputOutputBinding.class,
    TAuditing.class,
    TOutputSet.class,
    TDataOutput.class,
    TProperty.class,
    TRendering.class,
    TMonitoring.class,
    TLaneSet.class,
    TInputSet.class,
    TConversationLink.class,
    TMessageFlow.class,
    TResourceAssignmentExpression.class,
    TParticipantAssociation.class,
    TRelationship.class,
    TDataInput.class,
    TComplexBehaviorDefinition.class,
    TOperation.class,
    TResourceParameter.class,
    TParticipant.class,
    TCorrelationSubscription.class,
    TConversationNode.class,
    TArtifact.class,
    TDataState.class,
    TMessageFlowAssociation.class,
    TCategoryValue.class,
    TLoopCharacteristics.class,
    TCorrelationPropertyBinding.class,
    TInputOutputSpecification.class,
    TResourceRole.class,
    TDataAssociation.class,
    TCorrelationPropertyRetrievalExpression.class,
    TLane.class,
    TParticipantMultiplicity.class,
    TAssignment.class,
    TResourceParameterBinding.class,
    TRootElement.class,
    TCorrelationKey.class,
    TFlowElement.class
})
public abstract class TBaseElement {
    @objid ("756d4c3f-9511-4546-ae0d-6233ac6f2f42")
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    @objid ("717f1de1-393b-4ec8-b637-7b4cb24e18dc")
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    @objid ("918ca3d9-7bc6-4a42-8231-437a0e65f41e")
    protected List<TDocumentation> documentation;

    @objid ("bd3a19f4-80e1-4ee9-8a71-1dc1f8e64554")
    protected TExtensionElements extensionElements;

    /**
     * Gets the value of the documentation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getDocumentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDocumentation }
     */
    @objid ("c7d0b538-2c3a-4f3e-b2da-c9063b8f3bcc")
    public List<TDocumentation> getDocumentation() {
        if (this.documentation == null) {
            this.documentation = new ArrayList<>();
        }
        return this.documentation;
    }

    /**
     * Gets the value of the extensionElements property.
     * @return
     * possible object is
     * {@link TExtensionElements }
     */
    @objid ("830fc5f7-53db-4e14-ac20-530611217d6f")
    public TExtensionElements getExtensionElements() {
        return this.extensionElements;
    }

    /**
     * Sets the value of the extensionElements property.
     * @param value allowed object is
     * {@link TExtensionElements }
     */
    @objid ("ef84ddec-9405-4e28-b14e-e1b4738fbec4")
    public void setExtensionElements(TExtensionElements value) {
        this.extensionElements = value;
    }

    /**
     * Gets the value of the id property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("5b53d7bc-0842-44a9-8ff9-b076be85ab63")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("df81f7e5-9532-4e34-bbc8-d8829d7cb44e")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * @return
     * always non-null
     */
    @objid ("3cc4395c-4105-4c7c-b222-68f9de393825")
    public Map<QName, String> getOtherAttributes() {
        return this.otherAttributes;
    }

}
