/* 
 * Copyright 2013-2019 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tCompensateEventDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCompensateEventDefinition">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tEventDefinition">
 * &lt;attribute name="waitForCompletion" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="activityRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("daeaa3dd-ecbf-416c-99e3-88741d468c0f")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCompensateEventDefinition")
public class TCompensateEventDefinition extends TEventDefinition {
    @objid ("9a969dd1-9879-43b6-b389-259eb4c3b1f9")
    @XmlAttribute(name = "waitForCompletion")
    protected Boolean waitForCompletion;

    @objid ("50b6f9d9-f0ea-48ea-84d1-29194e809da5")
    @XmlAttribute(name = "activityRef")
    protected QName activityRef;

    /**
     * Gets the value of the waitForCompletion property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    @objid ("885adc4b-3e15-47c8-bc2f-b5ef4073ed11")
    public Boolean isWaitForCompletion() {
        return this.waitForCompletion;
    }

    /**
     * Sets the value of the waitForCompletion property.
     * 
     * @param value allowed object is
     * {@link Boolean }
     */
    @objid ("4e7edc56-0267-4d3e-bf3b-80e39a683879")
    public void setWaitForCompletion(Boolean value) {
        this.waitForCompletion = value;
    }

    /**
     * Gets the value of the activityRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("1aac86dd-be5e-487a-aa54-b766350fe307")
    public QName getActivityRef() {
        return this.activityRef;
    }

    /**
     * Sets the value of the activityRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("89557635-d24c-41e6-b8ec-0ad70e413896")
    public void setActivityRef(QName value) {
        this.activityRef = value;
    }

}
