/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * <p>Java class for tConversationLink complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tConversationLink">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tBaseElement">
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="sourceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;attribute name="targetRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("5f55c64c-e456-4b5c-b566-e514ce73b18f")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tConversationLink")
public class TConversationLink extends TBaseElement {
    @objid ("c2fcd8ac-56d9-4b46-9e11-67f707eca1c0")
    @XmlAttribute(name = "name")
    protected String name;

    @objid ("7308a0c1-ec8e-4706-b284-27df41c666fd")
    @XmlAttribute(name = "sourceRef", required = true)
    protected QName sourceRef;

    @objid ("4c5e2da2-82f3-42a8-919c-829efa5c1c8e")
    @XmlAttribute(name = "targetRef", required = true)
    protected QName targetRef;

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("a4354671-68db-41e1-863d-48d60c8d0816")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("8b8f3ffc-1a47-422a-b895-782f65d35d2c")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sourceRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("e0104ab5-ca3b-404f-bf06-8a675295dafb")
    public QName getSourceRef() {
        return this.sourceRef;
    }

    /**
     * Sets the value of the sourceRef property.
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("5b9b40ed-b393-43f3-a66c-3c1604c564c8")
    public void setSourceRef(QName value) {
        this.sourceRef = value;
    }

    /**
     * Gets the value of the targetRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("c063329a-9128-41bb-9e46-5e95fa548226")
    public QName getTargetRef() {
        return this.targetRef;
    }

    /**
     * Sets the value of the targetRef property.
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("2086f693-1d8f-4449-b602-40fe4bff0de6")
    public void setTargetRef(QName value) {
        this.targetRef = value;
    }

}
