/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tDataAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDataAssociation">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tBaseElement">
 * &lt;sequence>
 * &lt;element name="sourceRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="targetRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 * &lt;element name="transformation" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tFormalExpression" minOccurs="0"/>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}assignment" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("1811863f-4208-42a8-a3ca-b4343ef27bc7")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDataAssociation", propOrder = {
    "sourceRef",
    "targetRef",
    "transformation",
    "assignment"
})
@XmlSeeAlso({
    TDataInputAssociation.class,
    TDataOutputAssociation.class
})
public class TDataAssociation extends TBaseElement {
    @objid ("a14e3cce-f94f-4012-9be1-9fba67eaffd9")
    @XmlElementRef(name = "sourceRef", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<Object>> sourceRef;

    @objid ("dcd12ea7-9ea6-4894-9c53-a409b314c876")
    @XmlElement(required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object targetRef;

    @objid ("52693539-236a-4260-b9fc-55dd0b895571")
    protected TFormalExpression transformation;

    @objid ("7153eb57-e9fe-431b-9fe4-9ae667b07fbf")
    protected List<TAssignment> assignment;

    /**
     * Gets the value of the sourceRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getSourceRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @objid ("42b1c1a7-7843-4afe-8a95-48faff8b74ec")
    public List<JAXBElement<Object>> getSourceRef() {
        if (this.sourceRef == null) {
            this.sourceRef = new ArrayList<>();
        }
        return this.sourceRef;
    }

    /**
     * Gets the value of the targetRef property.
     * @return
     * possible object is
     * {@link Object }
     */
    @objid ("845915ae-92ae-469d-a0f3-65676eac26ae")
    public Object getTargetRef() {
        return this.targetRef;
    }

    /**
     * Sets the value of the targetRef property.
     * 
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("a38fac1c-3745-4628-8f1c-8054392d3498")
    public void setTargetRef(Object value) {
        this.targetRef = value;
    }

    /**
     * Gets the value of the transformation property.
     * @return
     * possible object is
     * {@link TFormalExpression }
     */
    @objid ("0c620dac-6b21-4275-bb30-cb4c192feb2c")
    public TFormalExpression getTransformation() {
        return this.transformation;
    }

    /**
     * Sets the value of the transformation property.
     * 
     * @param value allowed object is
     * {@link TFormalExpression }
     */
    @objid ("4811c8f7-e71e-4892-b3cf-8a1938a947f3")
    public void setTransformation(TFormalExpression value) {
        this.transformation = value;
    }

    /**
     * Gets the value of the assignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAssignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAssignment }
     */
    @objid ("fdf7ca42-5d81-45f2-b270-3f27f82893b8")
    public List<TAssignment> getAssignment() {
        if (this.assignment == null) {
            this.assignment = new ArrayList<>();
        }
        return this.assignment;
    }

}
