/* 
 * Copyright 2013-2019 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tDataObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDataObject">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tFlowElement">
 * &lt;sequence>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}dataState" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="itemSubjectRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;attribute name="isCollection" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("0f09c574-c060-46e0-a46f-00937a2bb8f6")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDataObject", propOrder = {
    "dataState"
})
public class TDataObject extends TFlowElement {
    @objid ("73821994-650b-4902-9120-a1f17f628b43")
    @XmlAttribute(name = "isCollection")
    protected Boolean isCollection;

    @objid ("247cf5cb-5a3b-49c3-90b4-0ee56b7ba612")
    protected TDataState dataState;

    @objid ("956b032d-e9da-4a35-aba9-0837c21d59f5")
    @XmlAttribute(name = "itemSubjectRef")
    protected QName itemSubjectRef;

    /**
     * Gets the value of the dataState property.
     * @return
     * possible object is
     * {@link TDataState }
     */
    @objid ("44bbdc2e-af76-4396-b1ad-4db1a8cae23a")
    public TDataState getDataState() {
        return this.dataState;
    }

    /**
     * Sets the value of the dataState property.
     * 
     * @param value allowed object is
     * {@link TDataState }
     */
    @objid ("f15dd97a-4ef0-4dc2-b950-4620e2dae844")
    public void setDataState(TDataState value) {
        this.dataState = value;
    }

    /**
     * Gets the value of the itemSubjectRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("69bbdb5a-9e20-4b8f-a5f8-dbd53ba9eeb7")
    public QName getItemSubjectRef() {
        return this.itemSubjectRef;
    }

    /**
     * Sets the value of the itemSubjectRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("a5473c17-b72f-4d95-8f56-ea5a93b0942c")
    public void setItemSubjectRef(QName value) {
        this.itemSubjectRef = value;
    }

    /**
     * Gets the value of the isCollection property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    @objid ("3825ea07-2510-432d-b5f9-c4692530e687")
    public boolean isIsCollection() {
        if (this.isCollection == null) {
            return false;
        } else {
            return this.isCollection;
        }
    }

    /**
     * Sets the value of the isCollection property.
     * 
     * @param value allowed object is
     * {@link Boolean }
     */
    @objid ("024ef3e7-a4d4-49ac-a024-0410139ecec0")
    public void setIsCollection(Boolean value) {
        this.isCollection = value;
    }

}
