/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * <p>Java class for tDefinitions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDefinitions">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}import" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}extension" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}rootElement" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/DI}BPMNDiagram" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}relationship" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="targetNamespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 * &lt;attribute name="expressionLanguage" type="{http://www.w3.org/2001/XMLSchema}anyURI" default="http://www.w3.org/1999/XPath" />
 * &lt;attribute name="typeLanguage" type="{http://www.w3.org/2001/XMLSchema}anyURI" default="http://www.w3.org/2001/XMLSchema" />
 * &lt;attribute name="exporter" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="exporterVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("89835529-ce7f-4de0-890b-24f63f8ddb52")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDefinitions", propOrder = {
    "_import",
    "extension",
    "rootElement",
    "bpmnDiagram",
    "relationship"
})
public class TDefinitions {
    @objid ("32e8f45d-9310-4d66-a6bb-61edee9c7ae6")
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    @objid ("0677a1dc-0027-4393-a809-f5ee01885ebf")
    @XmlAttribute(name = "name")
    protected String name;

    @objid ("93984513-9ce5-4493-816f-c7ee8aafc2ea")
    @XmlAttribute(name = "targetNamespace", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetNamespace;

    @objid ("0bcd1707-f471-4679-8481-30b8b2b9ce3f")
    @XmlAttribute(name = "expressionLanguage")
    @XmlSchemaType(name = "anyURI")
    protected String expressionLanguage;

    @objid ("76aa2158-ea55-421c-89c7-08627dd67c6d")
    @XmlAttribute(name = "typeLanguage")
    @XmlSchemaType(name = "anyURI")
    protected String typeLanguage;

    @objid ("f28c96c0-85a0-452e-a60d-0710df589faf")
    @XmlAttribute(name = "exporter")
    protected String exporter;

    @objid ("0533533a-cb55-445d-a368-b84e4f205257")
    @XmlAttribute(name = "exporterVersion")
    protected String exporterVersion;

    @objid ("6c14d4ea-1578-4709-be40-31fe8005c355")
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    @objid ("4e321ea1-e611-4640-995d-8e7444c226b1")
    @XmlElement(name = "import")
    protected List<TImport> _import;

    @objid ("d86de88e-7137-4782-8029-82067409dada")
    protected List<TExtension> extension;

    @objid ("bd44af79-00d3-4ffb-b8f2-391f9451bebb")
    @XmlElementRef(name = "rootElement", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends TRootElement>> rootElement;

    @objid ("60a6bffd-291d-4657-8d6a-cd9c447d7894")
    @XmlElement(name = "BPMNDiagram", namespace = "http://www.omg.org/spec/BPMN/20100524/DI")
    protected List<BPMNDiagram> bpmnDiagram;

    @objid ("8f29b706-88af-47f2-a8aa-bc2d3d5bbb4d")
    protected List<TRelationship> relationship;

    /**
     * Gets the value of the import property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the import property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getImport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TImport }
     */
    @objid ("0a32bdef-cee6-4cd7-be20-589b5c0d66a7")
    public List<TImport> getImport() {
        if (this._import == null) {
            this._import = new ArrayList<>();
        }
        return this._import;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TExtension }
     */
    @objid ("da45dd2c-e88b-46c2-9bd3-32b4fa769565")
    public List<TExtension> getExtension() {
        if (this.extension == null) {
            this.extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the rootElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rootElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getRootElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TCorrelationProperty }{@code >}
     * {@link JAXBElement }{@code <}{@link TProcess }{@code >}
     * {@link JAXBElement }{@code <}{@link TRootElement }{@code >}
     * {@link JAXBElement }{@code <}{@link TError }{@code >}
     * {@link JAXBElement }{@code <}{@link TInterface }{@code >}
     * {@link JAXBElement }{@code <}{@link TCollaboration }{@code >}
     * {@link JAXBElement }{@code <}{@link TPartnerRole }{@code >}
     * {@link JAXBElement }{@code <}{@link TItemDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TTerminateEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TEndPoint }{@code >}
     * {@link JAXBElement }{@code <}{@link TEscalationEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TConditionalEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TGlobalManualTask }{@code >}
     * {@link JAXBElement }{@code <}{@link TTimerEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TLinkEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TSignal }{@code >}
     * {@link JAXBElement }{@code <}{@link TGlobalConversation }{@code >}
     * {@link JAXBElement }{@code <}{@link TSignalEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TMessageEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TGlobalBusinessRuleTask }{@code >}
     * {@link JAXBElement }{@code <}{@link TCancelEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TEscalation }{@code >}
     * {@link JAXBElement }{@code <}{@link TMessage }{@code >}
     * {@link JAXBElement }{@code <}{@link TCategory }{@code >}
     * {@link JAXBElement }{@code <}{@link TPartnerEntity }{@code >}
     * {@link JAXBElement }{@code <}{@link TEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TDataStore }{@code >}
     * {@link JAXBElement }{@code <}{@link TGlobalChoreographyTask }{@code >}
     * {@link JAXBElement }{@code <}{@link TErrorEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TCompensateEventDefinition }{@code >}
     * {@link JAXBElement }{@code <}{@link TGlobalTask }{@code >}
     * {@link JAXBElement }{@code <}{@link TGlobalUserTask }{@code >}
     * {@link JAXBElement }{@code <}{@link TGlobalScriptTask }{@code >}
     * {@link JAXBElement }{@code <}{@link TChoreography }{@code >}
     * {@link JAXBElement }{@code <}{@link TResource }{@code >}
     */
    @objid ("c3ce0107-8680-44d6-935b-f1aeea1177c3")
    public List<JAXBElement<? extends TRootElement>> getRootElement() {
        if (this.rootElement == null) {
            this.rootElement = new ArrayList<>();
        }
        return this.rootElement;
    }

    /**
     * Gets the value of the bpmnDiagram property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bpmnDiagram property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getBPMNDiagram().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BPMNDiagram }
     */
    @objid ("e9def4e9-57b4-49ec-9986-fc52494cc75b")
    public List<BPMNDiagram> getBPMNDiagram() {
        if (this.bpmnDiagram == null) {
            this.bpmnDiagram = new ArrayList<>();
        }
        return this.bpmnDiagram;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRelationship }
     */
    @objid ("71dd0c69-c3f2-416f-9ccc-87394f73310d")
    public List<TRelationship> getRelationship() {
        if (this.relationship == null) {
            this.relationship = new ArrayList<>();
        }
        return this.relationship;
    }

    /**
     * Gets the value of the id property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("ef81e159-99ff-4c4e-843e-c69a51ac4904")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("c2374ccc-fa72-4949-b119-dbac5fc14377")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("056a0ada-800a-4597-b461-4b0e254fb6b0")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("c3a4d6ba-4438-474a-908d-659b4504976e")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the targetNamespace property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("a5c51d2d-9858-4637-92a8-c0778c8c0d37")
    public String getTargetNamespace() {
        return this.targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("32584c58-1d9b-442e-8a30-0413e45276cc")
    public void setTargetNamespace(String value) {
        this.targetNamespace = value;
    }

    /**
     * Gets the value of the expressionLanguage property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("e33a3f11-72a1-4f54-9b6a-34c2ceac4f69")
    public String getExpressionLanguage() {
        if (this.expressionLanguage == null) {
            return "http://www.w3.org/1999/XPath";
        } else {
            return this.expressionLanguage;
        }
        
    }

    /**
     * Sets the value of the expressionLanguage property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("b65cb34c-0946-4109-939d-1b2d7f744afa")
    public void setExpressionLanguage(String value) {
        this.expressionLanguage = value;
    }

    /**
     * Gets the value of the typeLanguage property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("6e44bf26-3ea6-4c8f-ada4-5b699e498462")
    public String getTypeLanguage() {
        if (this.typeLanguage == null) {
            return "http://www.w3.org/2001/XMLSchema";
        } else {
            return this.typeLanguage;
        }
        
    }

    /**
     * Sets the value of the typeLanguage property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("2d9523b9-6a4f-4278-9fe4-d2d8f79aaac6")
    public void setTypeLanguage(String value) {
        this.typeLanguage = value;
    }

    /**
     * Gets the value of the exporter property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("75fc8423-560c-4515-9aca-114651186b69")
    public String getExporter() {
        return this.exporter;
    }

    /**
     * Sets the value of the exporter property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("33423706-5fb5-4eb8-84b4-da622b2c3c28")
    public void setExporter(String value) {
        this.exporter = value;
    }

    /**
     * Gets the value of the exporterVersion property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("06cb3b7a-7835-4baf-904b-56e0ab493ce4")
    public String getExporterVersion() {
        return this.exporterVersion;
    }

    /**
     * Sets the value of the exporterVersion property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("f4bccc84-da8e-4a8d-a9a7-8927d3eeee45")
    public void setExporterVersion(String value) {
        this.exporterVersion = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * @return
     * always non-null
     */
    @objid ("9f84c293-8337-442e-bc81-2c2e1a1a6289")
    public Map<QName, String> getOtherAttributes() {
        return this.otherAttributes;
    }

}
