/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tLane complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tLane">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tBaseElement">
 * &lt;sequence>
 * &lt;element name="partitionElement" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tBaseElement" minOccurs="0"/>
 * &lt;element name="flowNodeRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="childLaneSet" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tLaneSet" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="partitionElementRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("aa5f8bbc-1995-4863-bb6d-b704bbcc27c8")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tLane", propOrder = {
    "partitionElement",
    "flowNodeRef",
    "childLaneSet"
})
public class TLane extends TBaseElement {
    @objid ("021057d9-3c62-4421-b194-69177dd22274")
    @XmlAttribute(name = "name")
    protected String name;

    @objid ("aabd42b5-e832-435a-8338-118c824fa47f")
    protected TBaseElement partitionElement;

    @objid ("e18ad8ab-571d-4889-8a93-7eba1cb3218c")
    @XmlElementRef(name = "flowNodeRef", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<Object>> flowNodeRef;

    @objid ("e9415070-ede6-4c90-9103-968091ecfbbb")
    protected TLaneSet childLaneSet;

    @objid ("b71993b1-28d3-4c35-a67b-d99d54e924e7")
    @XmlAttribute(name = "partitionElementRef")
    protected QName partitionElementRef;

    /**
     * Gets the value of the partitionElement property.
     * @return
     * possible object is
     * {@link TBaseElement }
     */
    @objid ("1546d632-1eda-411f-a1f9-6615d81cd310")
    public TBaseElement getPartitionElement() {
        return this.partitionElement;
    }

    /**
     * Sets the value of the partitionElement property.
     * 
     * @param value allowed object is
     * {@link TBaseElement }
     */
    @objid ("02e11623-1d40-467a-8016-90a126182254")
    public void setPartitionElement(TBaseElement value) {
        this.partitionElement = value;
    }

    /**
     * Gets the value of the flowNodeRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flowNodeRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getFlowNodeRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @objid ("fb777ae2-33d9-4a79-baba-bf92354ec7a0")
    public List<JAXBElement<Object>> getFlowNodeRef() {
        if (this.flowNodeRef == null) {
            this.flowNodeRef = new ArrayList<>();
        }
        return this.flowNodeRef;
    }

    /**
     * Gets the value of the childLaneSet property.
     * @return
     * possible object is
     * {@link TLaneSet }
     */
    @objid ("2d321b07-e31b-480f-bdf8-3c370b47eb96")
    public TLaneSet getChildLaneSet() {
        return this.childLaneSet;
    }

    /**
     * Sets the value of the childLaneSet property.
     * 
     * @param value allowed object is
     * {@link TLaneSet }
     */
    @objid ("0890cede-6a65-4cc8-b016-2111371d4b6d")
    public void setChildLaneSet(TLaneSet value) {
        this.childLaneSet = value;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("380d1100-46a8-4eec-9e00-5e98ae1fc85e")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    @objid ("c69a7da6-0c87-4980-aa99-8d48cc6fe102")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the partitionElementRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("9f072a68-fbb3-4aa4-8423-8ebf187f7a4c")
    public QName getPartitionElementRef() {
        return this.partitionElementRef;
    }

    /**
     * Sets the value of the partitionElementRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("2cfb3034-9245-40ae-b270-a89f30d4e2fa")
    public void setPartitionElementRef(QName value) {
        this.partitionElementRef = value;
    }

}
