/* 
 * Copyright 2013-2018 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tMessageFlowAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMessageFlowAssociation">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tBaseElement">
 * &lt;attribute name="innerMessageFlowRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;attribute name="outerMessageFlowRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("d56d4785-204a-4f2a-a25a-e1b425090648")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMessageFlowAssociation")
public class TMessageFlowAssociation extends TBaseElement {
    @objid ("c5619ee1-dfec-456f-a967-b880cd46bbb8")
    @XmlAttribute(name = "innerMessageFlowRef", required = true)
    protected QName innerMessageFlowRef;

    @objid ("1f5264fa-0db7-4515-af8c-2df1a69274ea")
    @XmlAttribute(name = "outerMessageFlowRef", required = true)
    protected QName outerMessageFlowRef;

    /**
     * Gets the value of the innerMessageFlowRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("bf334bc9-361d-493b-a6b8-077ba25112a3")
    public QName getInnerMessageFlowRef() {
        return this.innerMessageFlowRef;
    }

    /**
     * Sets the value of the innerMessageFlowRef property.
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("b0419c65-4e87-4cca-b5d2-a4b4aeb3c876")
    public void setInnerMessageFlowRef(QName value) {
        this.innerMessageFlowRef = value;
    }

    /**
     * Gets the value of the outerMessageFlowRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("2f162867-13c4-445a-94e1-ba958c25db61")
    public QName getOuterMessageFlowRef() {
        return this.outerMessageFlowRef;
    }

    /**
     * Sets the value of the outerMessageFlowRef property.
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("30b3b3a9-9e21-4b47-9cbd-96118b4dc5ac")
    public void setOuterMessageFlowRef(QName value) {
        this.outerMessageFlowRef = value;
    }

}
