/* 
 * Copyright 2013-2019 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tMessageFlow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMessageFlow">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tBaseElement">
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="sourceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;attribute name="targetRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;attribute name="messageRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("b999fb6d-8ece-4e28-94e2-f13d06165803")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMessageFlow")
public class TMessageFlow extends TBaseElement {
    @objid ("93cf3465-a5c6-414c-afd7-804b95e81a02")
    @XmlAttribute(name = "name")
    protected String name;

    @objid ("a34513f3-08af-426b-9413-12645f2ce2be")
    @XmlAttribute(name = "sourceRef", required = true)
    protected QName sourceRef;

    @objid ("f3e81852-42ae-4526-ad71-cf56b003abc7")
    @XmlAttribute(name = "targetRef", required = true)
    protected QName targetRef;

    @objid ("f812a853-dbef-4694-abb4-985f33d61adc")
    @XmlAttribute(name = "messageRef")
    protected QName messageRef;

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("057affc7-b432-4c33-9c6a-d0be04484bde")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    @objid ("53fd37e9-b164-4962-8942-8ed176008a41")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sourceRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("745a593e-e9fd-4816-9a55-ec64c8b308b9")
    public QName getSourceRef() {
        return this.sourceRef;
    }

    /**
     * Sets the value of the sourceRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("858ad36f-b551-4dc2-9e43-5f35f4aeb30c")
    public void setSourceRef(QName value) {
        this.sourceRef = value;
    }

    /**
     * Gets the value of the targetRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("473bbb8b-6052-4a79-b143-d681446f625a")
    public QName getTargetRef() {
        return this.targetRef;
    }

    /**
     * Sets the value of the targetRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("73efe15d-c20f-4e56-8efa-ab4c0c12d056")
    public void setTargetRef(QName value) {
        this.targetRef = value;
    }

    /**
     * Gets the value of the messageRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("3f136b65-c73b-4ace-bd86-52f92bc03fb6")
    public QName getMessageRef() {
        return this.messageRef;
    }

    /**
     * Sets the value of the messageRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("d7453107-70cf-4bd3-804d-e087b345600e")
    public void setMessageRef(QName value) {
        this.messageRef = value;
    }

}
