/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tOperation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOperation">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tBaseElement">
 * &lt;sequence>
 * &lt;element name="inMessageRef" type="{http://www.w3.org/2001/XMLSchema}QName"/>
 * &lt;element name="outMessageRef" type="{http://www.w3.org/2001/XMLSchema}QName" minOccurs="0"/>
 * &lt;element name="errorRef" type="{http://www.w3.org/2001/XMLSchema}QName" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="implementationRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("a358650d-0fd8-4f67-9b2e-6e4422624845")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOperation", propOrder = {
    "inMessageRef",
    "outMessageRef",
    "errorRef"
})
public class TOperation extends TBaseElement {
    @objid ("a91437da-7101-4017-8f6e-73bf6f2022bc")
    @XmlAttribute(name = "name", required = true)
    protected String name;

    @objid ("590ab8c2-57d9-4163-b80b-30254fc358ca")
    @XmlElement(required = true)
    protected QName inMessageRef;

    @objid ("16022b9f-dd39-4ff4-a255-4194b116b197")
    protected QName outMessageRef;

    @objid ("114df9d4-8388-4dfb-9a19-d0a4b0d61f8f")
    protected List<QName> errorRef;

    @objid ("07cf41c8-c9b0-41a8-9c7a-905997954989")
    @XmlAttribute(name = "implementationRef")
    protected QName implementationRef;

    /**
     * Gets the value of the inMessageRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("68d9ff69-91e5-4625-8f69-c9ed7953cf8b")
    public QName getInMessageRef() {
        return this.inMessageRef;
    }

    /**
     * Sets the value of the inMessageRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("821abb1c-b4a7-4a97-9925-bbe68912c0e5")
    public void setInMessageRef(QName value) {
        this.inMessageRef = value;
    }

    /**
     * Gets the value of the outMessageRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("6ab64aaa-97b4-4141-8066-a42981dcee8a")
    public QName getOutMessageRef() {
        return this.outMessageRef;
    }

    /**
     * Sets the value of the outMessageRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("5aa31914-1918-4905-963f-b9871ae5060c")
    public void setOutMessageRef(QName value) {
        this.outMessageRef = value;
    }

    /**
     * Gets the value of the errorRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getErrorRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QName }
     */
    @objid ("0ff7ad8e-492a-4222-aec3-ecda60fd30d8")
    public List<QName> getErrorRef() {
        if (this.errorRef == null) {
            this.errorRef = new ArrayList<>();
        }
        return this.errorRef;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("cac1306f-ff89-4397-b0ce-d89e802eeb6a")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    @objid ("2e1f8ec6-4305-4cb2-8a82-5a46c9f402f1")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the implementationRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("3164a4c1-7e26-4558-be5f-a4f662017865")
    public QName getImplementationRef() {
        return this.implementationRef;
    }

    /**
     * Sets the value of the implementationRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("daca15be-64e2-4b2f-ad03-9b9ca1e07673")
    public void setImplementationRef(QName value) {
        this.implementationRef = value;
    }

}
