/* 
 * Copyright 2013-2019 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for tReceiveTask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tReceiveTask">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tTask">
 * &lt;attribute name="implementation" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tImplementation" default="##WebService" />
 * &lt;attribute name="instantiate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 * &lt;attribute name="messageRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;attribute name="operationRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("f67ede0b-9481-473d-ae2e-4d4f604503d5")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tReceiveTask")
public class TReceiveTask extends TTask {
    @objid ("5b61a93b-bafa-421c-b0b9-32be1085928f")
    @XmlAttribute(name = "implementation")
    protected String implementation;

    @objid ("f562f9c2-fb7b-4718-9c6b-6499d4d15fb9")
    @XmlAttribute(name = "instantiate")
    protected Boolean instantiate;

    @objid ("3e0234c7-7b44-4727-80fb-1ae4c9746815")
    @XmlAttribute(name = "messageRef")
    protected QName messageRef;

    @objid ("bcc22609-b25c-431d-a31a-9c1ad727cb12")
    @XmlAttribute(name = "operationRef")
    protected QName operationRef;

    /**
     * Gets the value of the implementation property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("81e97e85-4c94-4b42-bbc1-d425e0913419")
    public String getImplementation() {
        if (this.implementation == null) {
            return "##WebService";
        } else {
            return this.implementation;
        }
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    @objid ("89a20b78-3d64-4f5b-a7eb-e26088ef9f17")
    public void setImplementation(String value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the instantiate property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    @objid ("f93cc907-a8e0-4f66-b4ec-c81682d36033")
    public boolean isInstantiate() {
        if (this.instantiate == null) {
            return false;
        } else {
            return this.instantiate;
        }
    }

    /**
     * Sets the value of the instantiate property.
     * 
     * @param value allowed object is
     * {@link Boolean }
     */
    @objid ("6f46cffc-5a95-4d3b-a28f-73d62d7c0dd9")
    public void setInstantiate(Boolean value) {
        this.instantiate = value;
    }

    /**
     * Gets the value of the messageRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("1331dca1-fd3c-41c9-9948-eb090488d0e9")
    public QName getMessageRef() {
        return this.messageRef;
    }

    /**
     * Sets the value of the messageRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("f7b4aa91-9bb5-48b3-856c-49969cdcdf00")
    public void setMessageRef(QName value) {
        this.messageRef = value;
    }

    /**
     * Gets the value of the operationRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("9d7595ab-ba61-429d-bde7-0af82ab09f64")
    public QName getOperationRef() {
        return this.operationRef;
    }

    /**
     * Sets the value of the operationRef property.
     * 
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("4819f0a7-c311-46ea-b3ca-a016234d9f4c")
    public void setOperationRef(QName value) {
        this.operationRef = value;
    }

}
