/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for tRelationshipDirection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tRelationshipDirection">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="None"/>
 * &lt;enumeration value="Forward"/>
 * &lt;enumeration value="Backward"/>
 * &lt;enumeration value="Both"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("02dda337-ebd7-4c4d-b89a-8457a5845d3b")
@XmlType(name = "tRelationshipDirection")
@XmlEnum
public enum TRelationshipDirection {
    @objid ("fbf73be9-efb8-4319-bb4e-4c7e2d041c1c")
    @XmlEnumValue("None")
    NONE("None"),
    @objid ("dafd3e8a-a771-48f5-819f-a2dcead638ca")
    @XmlEnumValue("Forward")
    FORWARD("Forward"),
    @objid ("dd73ce63-fdac-4d52-8945-68b16d7417d5")
    @XmlEnumValue("Backward")
    BACKWARD("Backward"),
    @objid ("70a1aafd-af10-48b5-a69c-b5b5b06f02cf")
    @XmlEnumValue("Both")
    BOTH("Both");

    @objid ("2a28ec48-68d6-419e-b948-58940e0adbcc")
    private final String value;

    @objid ("2a5db31a-dddc-46e9-b7f4-cd7e18db9c79")
     TRelationshipDirection(String v) {
        this.value = v;
    }

    @objid ("7238ac92-44db-47f5-b206-7c08364e3b1e")
    public String value() {
        return this.value;
    }

    @objid ("be6a59bc-e0ef-46aa-97d5-d621ddcae7df")
    public static TRelationshipDirection fromValue(String v) {
        for (TRelationshipDirection c: TRelationshipDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
        
    }

}
