/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for tSequenceFlow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSequenceFlow">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tFlowElement">
 * &lt;sequence>
 * &lt;element name="conditionExpression" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="sourceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;attribute name="targetRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;attribute name="isImmediate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("5f46dcad-dcef-4f9c-8552-0c1a24141746")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSequenceFlow", propOrder = {
    "conditionExpression"
})
public class TSequenceFlow extends TFlowElement {
    @objid ("0d2c5cca-3c09-4f54-946b-20aac6c8e94e")
    @XmlAttribute(name = "isImmediate")
    protected Boolean isImmediate;

    @objid ("55d3a835-f0ca-4b0e-a92c-016465dab7af")
    protected TExpression conditionExpression;

    @objid ("635ff7a4-56bb-4aaa-bbd1-02ba66f396f6")
    @XmlAttribute(name = "sourceRef", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object sourceRef;

    @objid ("1a7efab6-56ca-4526-ada5-01a86d6b242e")
    @XmlAttribute(name = "targetRef", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object targetRef;

    /**
     * Gets the value of the conditionExpression property.
     * @return
     * possible object is
     * {@link TExpression }
     */
    @objid ("3aad3a2f-6680-45dd-9ba6-d9782494341f")
    public TExpression getConditionExpression() {
        return this.conditionExpression;
    }

    /**
     * Sets the value of the conditionExpression property.
     * @param value allowed object is
     * {@link TExpression }
     */
    @objid ("0d3c521a-fc7e-45f4-ba62-f308553e08e4")
    public void setConditionExpression(TExpression value) {
        this.conditionExpression = value;
    }

    /**
     * Gets the value of the sourceRef property.
     * @return
     * possible object is
     * {@link Object }
     */
    @objid ("0fcaa8d4-30a9-4717-a438-786b6f2a60d7")
    public Object getSourceRef() {
        return this.sourceRef;
    }

    /**
     * Sets the value of the sourceRef property.
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("8f13c7f8-fa44-42bd-8cfa-3bb0f4067a6c")
    public void setSourceRef(Object value) {
        this.sourceRef = value;
    }

    /**
     * Gets the value of the targetRef property.
     * @return
     * possible object is
     * {@link Object }
     */
    @objid ("ef2b0330-3195-42d9-8a08-401560b37d08")
    public Object getTargetRef() {
        return this.targetRef;
    }

    /**
     * Sets the value of the targetRef property.
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("5082b2f8-d53d-44bf-8833-9a62e6f94142")
    public void setTargetRef(Object value) {
        this.targetRef = value;
    }

    /**
     * Gets the value of the isImmediate property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    @objid ("50dc3d0d-9e06-4f9b-889c-f71e6d817ca5")
    public Boolean isIsImmediate() {
        return this.isImmediate;
    }

    /**
     * Sets the value of the isImmediate property.
     * @param value allowed object is
     * {@link Boolean }
     */
    @objid ("c3c8a288-d8d3-4a93-860a-71f310f25add")
    public void setIsImmediate(Boolean value) {
        this.isImmediate = value;
    }

}
