/* 
 * Copyright 2013-2020 Modeliosoft
 * 
 * This file is part of Modelio.
 * 
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.02 at 02:29:48 PM CET
//
package org.modelio.bpmnxml.model;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * <p>Java class for tSignal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSignal">
 * &lt;complexContent>
 * &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tRootElement">
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="structureRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 * &lt;anyAttribute processContents='lax' namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("0c4ba7f9-95b7-4090-9312-c7faae4b08c8")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSignal")
public class TSignal extends TRootElement {
    @objid ("5416eb28-3f02-436c-ba41-e692c3f4e1d6")
    @XmlAttribute(name = "name")
    protected String name;

    @objid ("a9e4d80f-b0c1-4bdd-b686-938dafae7304")
    @XmlAttribute(name = "structureRef")
    protected QName structureRef;

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    @objid ("fba23a7c-7d80-4a3f-b3ba-ac406e984055")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    @objid ("37a54a6c-0f52-474f-a2da-bf13fd9a1547")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the structureRef property.
     * @return
     * possible object is
     * {@link QName }
     */
    @objid ("d43b116d-0d6c-4c6f-b53e-bd67eee70fc1")
    public QName getStructureRef() {
        return this.structureRef;
    }

    /**
     * Sets the value of the structureRef property.
     * @param value allowed object is
     * {@link QName }
     */
    @objid ("a7708840-1dfa-4907-8e7e-323eb82f3922")
    public void setStructureRef(QName value) {
        this.structureRef = value;
    }

}
