// Disable all captions for figures.
:!figure-caption:
// Path to the stylesheet files
:stylesdir: .

[[Audit-rules-list]]

[[audit-rules-list]]
= Audit rules list

* *<<Modeler_audit_rules_R1000.adoc#,R1000>>*: A Model Element cannot abstract itself.
* *<<Modeler_audit_rules_R1010.adoc#,R1010>>*: The top Partitions of an Activity must not have a Super-Partition.
* *<<Modeler_audit_rules_R1020.adoc#,R1020>>*: The source and the target of a Flow must be contained in the same Structured Activity Node.
* *<<Modeler_audit_rules_R1030.adoc#,R1030>>*: The source and the target of a Flow must be owned by the same Activity.
* *<<Modeler_audit_rules_R1040.adoc#,R1040>>*: An Activity Parameter Node must be represeneted by a Behavior Parameter owned by the same Activity.
* *<<Modeler_audit_rules_R1050.adoc#,R1050>>*: An Activity Parameter Node cannot have both incoming and outgoing edges.
* *<<Modeler_audit_rules_R1060.adoc#,R1060>>*: Activity Parameter Nodes with no incoming flow and one or more outgoing flow must have a Behavior Parameter with "In" or "In/Out" parameter passing mode.
* *<<Modeler_audit_rules_R1070.adoc#,R1070>>*: Activity Parameter Nodes with no outgoing flow and one or more incoming flow must have a Behavior Parameter with "Out" or "In/Out" parameter passing mode.
* *<<Modeler_audit_rules_R1080.adoc#,R1080>>*: All Partitions of the same nesting level must represent Parts of the same Classifier.
* *<<Modeler_audit_rules_R1090.adoc#,R1090>>*: If a Sub-Partition is non-external and represents a Classifier then the represented Classifier must be nested in the Classifier represented by its Super-Partition or be the extremity of a Composition with the latter.
* *<<Modeler_audit_rules_R1100.adoc#,R1100>>*: If a Sub-Partition represents a Part nested in a Classifier then its Super-Partition must represent the Classifier or an instance of the latter.
* *<<Modeler_audit_rules_R1110.adoc#,R1110>>*: There must be one to one correspondence between: (A) the Pins of a Call Behavior Action, and (B) the In, Out, InOut or Return Behavior Parameters of the called Behaviour.
* *<<Modeler_audit_rules_R1130.adoc#,R1130>>*: The type and the maximum cardinality of a Call Action''s Pin must match the type and max multiplicity of the represented Parameter.
* *<<Modeler_audit_rules_R1140.adoc#,R1140>>*: There must be one to one correspondence between: (A) the Pins of a Call Operation Action, and (B) the In, Inout, Out and Return parameters of the called Operation.
* *<<Modeler_audit_rules_R1150.adoc#,R1150>>*: The Call Operation Action or Send Signal Action has more than one target Pin.
* *<<Modeler_audit_rules_R1160.adoc#,R1160>>*: A target Pin can only be owned by Call Operation Actions and Send Signal Actions
* *<<Modeler_audit_rules_R1170.adoc#,R1170>>*: The type of the target Pin must be the same as the type that owns the Operation.
* *<<Modeler_audit_rules_R1180.adoc#,R1180>>*: Control Flows may not have Object Nodes at either end, except for Object Nodes with control type.
* *<<Modeler_audit_rules_R1190.adoc#,R1190>>*: The Decision-Merge Node is used both as a Decision node and as a Merge node at the same time.
* *<<Modeler_audit_rules_R1200.adoc#,R1200>>*: The edges coming into and out of a Decision Merge Node must be either all Object Flows or all Control Flows.
* *<<Modeler_audit_rules_R1230.adoc#,R1230>>*: Only Control Flows can have Initial Nodes as their source.
* *<<Modeler_audit_rules_R1250.adoc#,R1250>>*: If a Fork/Join Node has an Object Flow in its incoming edges, it must have an Object Flow in its outgoing edges and vice versa. The same applies for Control Flows.
* *<<Modeler_audit_rules_R1280.adoc#,R1280>>*: Object Flows may not have Actions at both end.
* *<<Modeler_audit_rules_R1290.adoc#,R1290>>*: Object Nodes connected by an Object Flow, with optionally intervening control nodes, must have compatible types. In particular, the downstream Object Node type must be the same or a super type of the upstream Object Node type.
* *<<Modeler_audit_rules_R1300.adoc#,R1300>>*: Object Nodes connected by an Object Flow, with optionally intervening control nodes, must have the same upper bounds.
* *<<Modeler_audit_rules_R1310.adoc#,R1310>>*: An edge with constant weight may not target an Object Node, or lead to an Object Node downstream with no intervening actions and with an upper bound less than the weight.
* *<<Modeler_audit_rules_R1320.adoc#,R1320>>*: An Object Flow must not be simultaneusly multi-cast and multi-receive.
* *<<Modeler_audit_rules_R1350.adoc#,R1350>>*: If an Object Node has a ''Selection behavior'', then the ''Ordering'' of the Object Node is ordered and vice versa.
* *<<Modeler_audit_rules_R1360.adoc#,R1360>>*: Input Pins may have outgoing edges only when both the following conditions are met: (1) they are on Actions that are Structured Nodes, and (2) these edges must target a Node contained by the Structured Node.
* *<<Modeler_audit_rules_R1370.adoc#,R1370>>*: Output Pins may have incoming edges only when both the following conditions are met: (1) they are on Actions that are Structured Nodes, and (2) these edges must come from a node contained by the Structured Node.
* *<<Modeler_audit_rules_R1380.adoc#,R1380>>*: There must be one to one correspondence between: (A) the Pins of a Send Signal Action, and (B) the attributes of the sent Signal.
* *<<Modeler_audit_rules_R1390.adoc#,R1390>>*: The max cardinality of an argument Pin must be the same as for the represented Attribute.
* *<<Modeler_audit_rules_R1400.adoc#,R1400>>*: An Activity Parameter Node can only belong to an Activity.
* *<<Modeler_audit_rules_R1410.adoc#,R1410>>*: Only one Association End of an Association can be aggregate or composite.
* *<<Modeler_audit_rules_R1420.adoc#,R1420>>*: Actors and UseCases can only have binary Associations.
* *<<Modeler_audit_rules_R1430.adoc#,R1430>>*: Multiplicities of an AssociationEnd must be consistent: MultiplicityMin cannot be '*' and MultiplicityMin must be inferior to MultiplicityMax.
* *<<Modeler_audit_rules_R1450.adoc#,R1450>>*: If an association is a composition, then the opposite maximum multiplicity must be 1.
* *<<Modeler_audit_rules_R1460.adoc#,R1460>>*: A public association oriented from a public Classifier cannot be linked to a private or protected Classifier.
* *<<Modeler_audit_rules_R1470.adoc#,R1470>>*: The name of an AssociationEnd's qualifiers must be unique.
* *<<Modeler_audit_rules_R1480.adoc#,R1480>>*: An Attribute must be typed by a primitive type.
* *<<Modeler_audit_rules_R1490.adoc#,R1490>>*: In an instance, the type of an instantiated attribute must be in the instantiated class or in its parent classes.
* *<<Modeler_audit_rules_R1500.adoc#,R1500>>*: In an instance, the name of an instantiated attribute must be the same as the corresponding attribute.
* *<<Modeler_audit_rules_R1520.adoc#,R1520>>*: The name of a BindableInstance must be unique in it Classifier.
* *<<Modeler_audit_rules_R1530.adoc#,R1530>>*: An association or a port should have a name.
* *<<Modeler_audit_rules_R1540.adoc#,R1540>>*: A BindableInstance's RepresentedFeature must not refer itself, directly or indirectly.
* *<<Modeler_audit_rules_R1550.adoc#,R1550>>*: If a BinbdableInstance has a type and has a represented feature, the type of the instance must be compatible with the type of this feature.
* *<<Modeler_audit_rules_R1560.adoc#,R1560>>*: Sub classes of an active class must be active.
* *<<Modeler_audit_rules_R1580.adoc#,R1580>>*: Attributes, Associations and Operations cannot simultaneously be abstract and class.
* *<<Modeler_audit_rules_R1590.adoc#,R1590>>*: Primitive GeneralClass cannot have associations.
* *<<Modeler_audit_rules_R1600.adoc#,R1600>>*: A primitive class cannot have collaborations.
* *<<Modeler_audit_rules_R1610.adoc#,R1610>>*: A primitive class cannot have state machines.
* *<<Modeler_audit_rules_R1620.adoc#,R1620>>*: A non-abstract Classifier cannot have abstract methods.
* *<<Modeler_audit_rules_R1640.adoc#,R1640>>*: A maximum of one ElementImport must exist between a NameSpace and another NameSpace or between an Operation and a NameSpace.
* *<<Modeler_audit_rules_R1650.adoc#,R1650>>*: An Enumeration cannot be abstract.
* *<<Modeler_audit_rules_R1660.adoc#,R1660>>*: An enumeration is always primitive.
* *<<Modeler_audit_rules_R1670.adoc#,R1670>>*: EnumlerationLitteral defined in an Enumeration must have an unique name.
* *<<Modeler_audit_rules_R1680.adoc#,R1680>>*: For a Call-type Event, the 'Called operation' field must be defined, whereas the 'Instanciated signal' must be empty.
* *<<Modeler_audit_rules_R1690.adoc#,R1690>>*: The 'Expression' field for a Change-type Event must be defined, whereas the 'Called operation' and 'Instanciated signal' fields must be empty.
* *<<Modeler_audit_rules_R1700.adoc#,R1700>>*: The 'Instantiated signal' field for a signal-type Event must be defined, whereas the 'Called operation' and 'Expression' fields must be empty.
* *<<Modeler_audit_rules_R1710.adoc#,R1710>>*: The 'Expression' field for a Time-type Event must be defined, whereas the 'Called operation' and 'Instanciated signal' fields must be empty.
* *<<Modeler_audit_rules_R1720.adoc#,R1720>>*: An abstract NameSpace should only inherit from an abstract NameSpace.
* *<<Modeler_audit_rules_R1730.adoc#,R1730>>*: A generalisation must be created between two model elements of the same type, except in the case of a signal, which can specialize a Signal or a Class.
* *<<Modeler_audit_rules_R1740.adoc#,R1740>>*: An InformationFlow should convey information.
* *<<Modeler_audit_rules_R1750.adoc#,R1750>>*: Repetition of names is forbidden for all AtrributeLinks.
* *<<Modeler_audit_rules_R1760.adoc#,R1760>>*: There cannot be inconsistency in the multiplicities of an Instance
* *<<Modeler_audit_rules_R1780.adoc#,R1780>>*: The name of an Instance must be unique in its NameSpace.
* *<<Modeler_audit_rules_R1790.adoc#,R1790>>*: An instance must have a name, or the instantiation association must be defined.
* *<<Modeler_audit_rules_R1800.adoc#,R1800>>*: If an Operator is of type opt, loop, break or neg, there cannot be more than one Operand.
* *<<Modeler_audit_rules_R1810.adoc#,R1810>>*: An actual Gate on an InteractionUse must reference a formal Gate contained by the referenced Interaction.
* *<<Modeler_audit_rules_R1820.adoc#,R1820>>*: A gate cannot cover a lifeline.
* *<<Modeler_audit_rules_R1830.adoc#,R1830>>*: A PartDecomposition cannot receive 'create' or 'destroy' messages.
* *<<Modeler_audit_rules_R1860.adoc#,R1860>>*: In an interface, the visibility of all Features must be public.
* *<<Modeler_audit_rules_R1870.adoc#,R1870>>*: An interface cannot be implemented twice by the same class or the same component.
* *<<Modeler_audit_rules_R1910.adoc#,R1910>>*: A Link that instantiates an association must be coherent with this association.
* *<<Modeler_audit_rules_R1950.adoc#,R1950>>*: Messages of type 'reply' cannot invoke an Operation.
* *<<Modeler_audit_rules_R1960.adoc#,R1960>>*: A message must have the same name as the invoked Operation.
* *<<Modeler_audit_rules_R1970.adoc#,R1970>>*: A TemplateParameterSubstitution must reference a TemplateParameter.
* *<<Modeler_audit_rules_R1980.adoc#,R1980>>*: The names of a Classifier's Attributes and AssociationEnds must be unique.
* *<<Modeler_audit_rules_R1990.adoc#,R1990>>*: The name of a Classifier's inherited Attributes and Roles must be unique.
* *<<Modeler_audit_rules_R2010.adoc#,R2010>>*: In a Dictionary, the name of each element must be unique.
* *<<Modeler_audit_rules_R2030.adoc#,R2030>>*: In a PropertyContainer, the name of each EnumerationPropertyType must be unique.
* *<<Modeler_audit_rules_R2050.adoc#,R2050>>*: Some elements must have a name.
* *<<Modeler_audit_rules_R2060.adoc#,R2060>>*: The name of a NameSpace must be unique in its NameSpace.
* *<<Modeler_audit_rules_R2080.adoc#,R2080>>*: In a PropertySet, the name of each Property must be unique.
* *<<Modeler_audit_rules_R2100.adoc#,R2100>>*: In a EnumerationPropertyType, the name of each PropertyEnumerationLiteral must be unique.
* *<<Modeler_audit_rules_R2120.adoc#,R2120>>*: In a PropertyContainer, the name of each PropertySet must be unique.
* *<<Modeler_audit_rules_R2140.adoc#,R2140>>*: In a PropertyContainer, the name of each PropertyType must be unique.
* *<<Modeler_audit_rules_R2160.adoc#,R2160>>*: In an Analyst Container, the name of each element must be unique.
* *<<Modeler_audit_rules_R2170.adoc#,R2170>>*: The name of a Behavior must be unique in its NameSpace.
* *<<Modeler_audit_rules_R2180.adoc#,R2180>>*: No cycles can exist in a NameSpace inheritance graph.
* *<<Modeler_audit_rules_R2190.adoc#,R2190>>*: A maximum of one generalization may exist between two namespaces.
* *<<Modeler_audit_rules_R2200.adoc#,R2200>>*: A NameSpace cannot both derive and import another NameSpace.
* *<<Modeler_audit_rules_R2210.adoc#,R2210>>*: A leaf NameSpace cannot be derived.
* *<<Modeler_audit_rules_R2220.adoc#,R2220>>*: A leaf NameSpace cannot be abstract.
* *<<Modeler_audit_rules_R2230.adoc#,R2230>>*: A root NameSpace cannot inherit from any other NameSpace.
* *<<Modeler_audit_rules_R2240.adoc#,R2240>>*: There can be no inter-package/inter-component dependency cycle.
* *<<Modeler_audit_rules_R2250.adoc#,R2250>>*: All operations in a Classifier must have a different signature from inherited public and protected operations. Except for constructor, destructor and redefined operations.
* *<<Modeler_audit_rules_R2260.adoc#,R2260>>*: Each Operation in a Classifer must have a different signature.
* *<<Modeler_audit_rules_R2270.adoc#,R2270>>*: All an Operation's Collaborations must have a different name.
* *<<Modeler_audit_rules_R2330.adoc#,R2330>>*: All an Operation's Parameters must have a different name.
* *<<Modeler_audit_rules_R2340.adoc#,R2340>>*: A redefined Operation must belong to a parent or an implemented Interface of the owner of the Operation.
* *<<Modeler_audit_rules_R2350.adoc#,R2350>>*: A private Operation cannot be redefined.
* *<<Modeler_audit_rules_R2360.adoc#,R2360>>*: The visibility of an Operation cannot be greater than that of the Operations it redefines.
* *<<Modeler_audit_rules_R2370.adoc#,R2370>>*: A class (static) Operation cannot be redefined.
* *<<Modeler_audit_rules_R2380.adoc#,R2380>>*: An abstract Operation must not redefine a concrete Operation.
* *<<Modeler_audit_rules_R2390.adoc#,R2390>>*: A constructor cannot have return parameters.
* *<<Modeler_audit_rules_R2400.adoc#,R2400>>*: A destructor cannot have any kind of parameters.
* *<<Modeler_audit_rules_R2410.adoc#,R2410>>*: An operation cannot own both 'create' and 'destroy' stereotypes.
* *<<Modeler_audit_rules_R2420.adoc#,R2420>>*: An Operation must have the same signature as the Operation it redefines.
* *<<Modeler_audit_rules_R2430.adoc#,R2430>>*: All an Operation's StateMachines must have a different name.
* *<<Modeler_audit_rules_R2440.adoc#,R2440>>*: An Operation cannot belong to an Enumeration.
* *<<Modeler_audit_rules_R2450.adoc#,R2450>>*: A package cannot have inheritance links.
* *<<Modeler_audit_rules_R2470.adoc#,R2470>>*: A maximum of one PackageImport link may exist between a NameSpace and a Package.
* *<<Modeler_audit_rules_R2500.adoc#,R2500>>*: An 'out' Parameter cannot have a default value.
* *<<Modeler_audit_rules_R2510.adoc#,R2510>>*: There cannot be any direct link between two Class Ports.
* *<<Modeler_audit_rules_R2520.adoc#,R2520>>*: If a Port runs a delegation towards an internal part, it must provide at least one interface.
* *<<Modeler_audit_rules_R2530.adoc#,R2530>>*: If a Port receives a delegation from an internal part, it must provide at least one interface.
* *<<Modeler_audit_rules_R2540.adoc#,R2540>>*: The interfaces provided by a port must be implemented by the Class that types the Port.
* *<<Modeler_audit_rules_R2550.adoc#,R2550>>*: If a Port is a behavior port, its provided interfaces must be implemented by the Class it belongs to.
* *<<Modeler_audit_rules_R2560.adoc#,R2560>>*: A behavior Port must provide at least one interface.
* *<<Modeler_audit_rules_R2570.adoc#,R2570>>*: If a Port is a behavior port, the type of the port must be either the Class it belongs to or undefined.
* *<<Modeler_audit_rules_R2580.adoc#,R2580>>*: A region cannot contain more than one deep history state.
* *<<Modeler_audit_rules_R2590.adoc#,R2590>>*: A region cannot contains more than one initial state.
* *<<Modeler_audit_rules_R2600.adoc#,R2600>>*: A state machine or a state cannot have two states with the same name.
* *<<Modeler_audit_rules_R2610.adoc#,R2610>>*: Only submachine states can have connection point references.
* *<<Modeler_audit_rules_R2620.adoc#,R2620>>*: Submachine states should not have entry or exit pseudo states defined.
* *<<Modeler_audit_rules_R2630.adoc#,R2630>>*: A region cannot contain more than one shallow history state.
* *<<Modeler_audit_rules_R2640.adoc#,R2640>>*: The context of a state machine cannot be an interface.
* *<<Modeler_audit_rules_R2650.adoc#,R2650>>*: The context of a protocol state machine must be a Classifier.
* *<<Modeler_audit_rules_R2660.adoc#,R2660>>*: A state in a protocol state machine cannot have entry, exit, or do activity actions.
* *<<Modeler_audit_rules_R2670.adoc#,R2670>>*: A protocol state machine cannot have history vertexes.
* *<<Modeler_audit_rules_R2680.adoc#,R2680>>*: The number of parameter of a TaggedValue must be the same as the number of parameter defined in the TaggedValue declaration.
* *<<Modeler_audit_rules_R2690.adoc#,R2690>>*: An element cannot have a TemplateBinding towards itself.
* *<<Modeler_audit_rules_R2700.adoc#,R2700>>*: A TemplateBinding can only substitute each TemplateParameter of the instantiated element once.
* *<<Modeler_audit_rules_R2720.adoc#,R2720>>*: A TemplateBinding must be created between two elements of the same type or between a Class and a DataType.
* *<<Modeler_audit_rules_R2730.adoc#,R2730>>*: A TemplateBinding must substitute all the TemplateParameters of the instanciated template element, and the TemplateParameterSubstitution must be defines in the same order as the TemplateParameters.
* *<<Modeler_audit_rules_R2740.adoc#,R2740>>*: In a TemplateBinding, the TemplateParameterSubstitution must belong to the instantiated template element.
* *<<Modeler_audit_rules_R2750.adoc#,R2750>>*: A transition from a fork or join pseudo state should not have guards or triggers.
* *<<Modeler_audit_rules_R2760.adoc#,R2760>>*: A fork segment must always target a state.
* *<<Modeler_audit_rules_R2770.adoc#,R2770>>*: A join segment must always originate from a state.
* *<<Modeler_audit_rules_R2780.adoc#,R2780>>*: Transitions outgoing pseudostates may not have a trigger (except for those coming out of the initial pseudostate).
* *<<Modeler_audit_rules_R2790.adoc#,R2790>>*: A transition from one region to another in the same immediate enclosing composite state is not allowed.
* *<<Modeler_audit_rules_R2800.adoc#,R2800>>*: An initial vertex can have at most one outgoing transition.
* *<<Modeler_audit_rules_R2810.adoc#,R2810>>*: History vertices can have at most one outgoing transition.
* *<<Modeler_audit_rules_R2820.adoc#,R2820>>*: The target of a transition cannot be an initial vertex.
* *<<Modeler_audit_rules_R2830.adoc#,R2830>>*: The source of a transition cannot be a final vertex.
* *<<Modeler_audit_rules_R2840.adoc#,R2840>>*: A transition should have only one of Processed, Effects, or BehaviorEffet defined.
* *<<Modeler_audit_rules_R2850.adoc#,R2850>>*: An element cannot have a usage dependency towards itself.
* *<<Modeler_audit_rules_R2860.adoc#,R2860>>*: A maximum of one extension/inclusion relationship may exist between two Use Cases.
* *<<Modeler_audit_rules_R2870.adoc#,R2870>>*: There must be no cycle in Use Cases extension relationship graph.
* *<<Modeler_audit_rules_R2880.adoc#,R2880>>*: There must be no cycle in Use Cases inclusion relationship graph.
* *<<Modeler_audit_rules_R2890.adoc#,R2890>>*: A communication link cannot have the same Actor or Use Case as its source and target.
* *<<Modeler_audit_rules_R2900.adoc#,R2900>>*: An extension relationship must reference at least one Extension Point.
* *<<Modeler_audit_rules_R2910.adoc#,R2910>>*: An extension relationship can only reference the target's Extension Points.
* *<<Modeler_audit_rules_R2920.adoc#,R2920>>*: Extension Points can only be referenced by an extension relationship.
* *<<Modeler_audit_rules_R2930.adoc#,R2930>>*: Message and Communication Message cannot have both Signal and Operation properties defined.
* *<<Modeler_audit_rules_R2940.adoc#,R2940>>*: All transitions incoming a join vertex must originate in different regions of an orthogonal state.
* *<<Modeler_audit_rules_R2950.adoc#,R2950>>*: All transitions outgoing a fork vertex must target states in different regions of an orthogonal state.
* *<<Modeler_audit_rules_R2960.adoc#,R2960>>*: Synonym, antonym, homonym, context, and kind-of dependencies can only link two terms.
* *<<Modeler_audit_rules_R2970.adoc#,R2970>>*: An Assigned dependency must be from an Actor, an Interface, a Package, or a Process, toward a Goal.
* *<<Modeler_audit_rules_R2980.adoc#,R2980>>*: A Measure dependency must be from a ModelElement toward a Goal.
* *<<Modeler_audit_rules_R2990.adoc#,R2990>>*: A Guarantee dependency must be from a Requirement toward a Goal.
* *<<Modeler_audit_rules_R3000.adoc#,R3000>>*: Positive influence and Negative influence dependencies must be between two Goals.
* *<<Modeler_audit_rules_R3010.adoc#,R3010>>*: A refers dependency must be between a Business Rule and a Term.
* *<<Modeler_audit_rules_R3020.adoc#,R3020>>*: A related dependency must be must be between two Business Rules or two Terms.
* *<<Modeler_audit_rules_R3030.adoc#,R3030>>*: A refine dependency must be between either: 1) from a Model Element or a Requirement towards a Requirement 2) from a Business Rule, an Activity or an Operation towards a Business Rule.
* *<<Modeler_audit_rules_R3040.adoc#,R3040>>*: An implement dependency must be from a Process or a Class towards a Business Rule.
* *<<Modeler_audit_rules_R3050.adoc#,R3050>>*: A part dependency must be between two Requirements or between two Goals.
* *<<Modeler_audit_rules_R3060.adoc#,R3060>>*: A satisfy or verify dependency must be from a ModelElement towards a Requirement.
* *<<Modeler_audit_rules_R3070.adoc#,R3070>>*: A derive dependency must be from a UseCase or a Requirement towards a Requirement.
* *<<Modeler_audit_rules_R3080.adoc#,R3080>>*: All FlowNodes should be part of a sequence starting with a StartEvent and finishing with an EndEvent.
* *<<Modeler_audit_rules_R3090.adoc#,R3090>>*: A SequenceFlow cannot have its source or target in different Process.
* *<<Modeler_audit_rules_R3100.adoc#,R3100>>*: A SequenceFlow in a SubProcess must have its origin and target in the same SubProcess.
* *<<Modeler_audit_rules_R3110.adoc#,R3110>>*: A SequenceFlow cannot target a StartEvent nor have an EndEvent as its source.
* *<<Modeler_audit_rules_R3120.adoc#,R3120>>*: A LinkThrowEvent must be linked to a LinkCatchEvent.
* *<<Modeler_audit_rules_R3130.adoc#,R3130>>*: A MessageFlow cannot target an EndEvent or an IntermediateThrowEvent, or have a StartEvent or an IntermediateCatchEvent as its source.
* *<<Modeler_audit_rules_R3140.adoc#,R3140>>*: All outgoing SequenceFlow from an EventBasedGateway or a ParallelGateway must have its guard empty.
* *<<Modeler_audit_rules_R3150.adoc#,R3150>>*: A MessageFlow cannot link two elements in the same Process.
* *<<Modeler_audit_rules_R3160.adoc#,R3160>>*: A MessageFlow cannot have a Gateway as its source or target.
* *<<Modeler_audit_rules_R3180.adoc#,R3180>>*: A FlowElement (and respectively a BaseElement) cannot have a SequenceFlow (respectively a MessageFlow) towards itself.
* *<<Modeler_audit_rules_R3190.adoc#,R3190>>*: A DataAssociation cannot target a DataInput nor have a DataOutput as its source.
* *<<Modeler_audit_rules_R3200.adoc#,R3200>>*: A LinkThrowEvent should have the same name as the targeted LinkCatchEvent .
* *<<Modeler_audit_rules_R3220.adoc#,R3220>>*: A SequenceFlow outgoing from an EventBasedGateway must target an IntermediaryCatchEvent.
* *<<Modeler_audit_rules_R3230.adoc#,R3230>>*: All SequenceFlows outgoing from an ExclusiveGateway must have a guard, except for the default SequenceFlow.
* *<<Modeler_audit_rules_R3250.adoc#,R3250>>*: Process and SubProcess should have at least one StartEvent and one EndEvent.
* *<<Modeler_audit_rules_R3260.adoc#,R3260>>*: The model should not contain missing elements.
* *<<Modeler_audit_rules_R3270.adoc#,R3270>>*: The State of a BpmnItemAwareElement must belong to its represented GeneralClass.
* *<<Modeler_audit_rules_R3280.adoc#,R3280>>*: A FlowElement must be part of a lane.
* *<<Modeler_audit_rules_R3290.adoc#,R3290>>*: A SequenceFlow must exist to support DataAssociations.
* *<<Modeler_audit_rules_R3300.adoc#,R3300>>*: Analyst elements must have a non-empty name.
* *<<Modeler_audit_rules_R3310.adoc#,R3310>>*: Dependency should follow recommended direction in Analyst models.
* *<<Modeler_audit_rules_R3320.adoc#,R3320>>*: A MessageFlow should start from a SendTask/ThrowEvent/Participant and end on a ReceiveTask/CatchEvent/Participant.
* *<<Modeler_audit_rules_R4000.adoc#,R4000>>* : The relationships must comply with the ArchiMate standard.
* *<<Modeler_audit_rules_R4010.adoc#,R4010>>* : The relationships to and from a Junction must be of the same kind.


